### ISSUE TITLE
Webroot plugin should support SANs (multiple public_html paths)

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1016]

**Comment by centminmod** [comment]
hopefully soon https://community.letsencrypt.org/t/multi-domain-san-certificate-and-webroot-auth/2493

Maybe this suggestion https://github.com/letsencrypt/letsencrypt/pull/757#issuecomment-1425074155

> for multiple names, maybe allow multiple --webroot-path in an array and then if multiple -d nameXX are specified cycle through the --webroot-path array to check against the -d name XX values ?

**Comment by kuba** [comment]
FYI I have created https://github.com/kuba/simp_le that is basically equivalent to webroot, but a lot simpler, with less deps and with renewal support. @centminmod, check it out :)

**Comment by kuba** [comment]
And, of course, with multiple SAN support.

**Comment by pde** [comment]
Currently I think a better CLI design for this may be, `letsencrypt --webroot -w /var/www/example -d example.com -d www.example.com -w /var/www/thingimy -d thingimy.net -d www.thingimy.net`.

**Comment by bmw** [comment]
@centminmod, I'm not sure if I understand your suggestion for this. Can you give me an example CLI stating which webroot would be applied for which domains?

**Comment by bmw** [comment]
Lately, I've been thinking a lot about multiple webroots and today I've been thinking about how to best specify them on the command line. The interface proposed in #1594 is pretty good, but I'm wondering if that's the best approach. Sure, we could always change the interface later, but I'd rather take a few extra days to get the interface right the first time instead of causing a breaking change later.

Unfortunately, I haven't been able to come up with a CLI I really like. The main problem I'm having is mapping webroots to domains. The way I see it, there are a couple approaches:

#### Include mapping in webroot-path flag
This looks something like `--webroot-path /var/www/html:example.com`. My main problem here is duplication. If you're specifying everything on the command line, you must include `--domains` meaning that you have to specify each domain in both `--webroot-path` and in `--domains`. This is excessive.

We can optimize this approach, however. The best I have come up with is using a range in `--webroot-path`, similar to how you specify lines in `git blame`. For example, 
```
letsencrypt --webroot --domains example.com,www.example.com,example.org,www.example.org,example.net,www.example.net --webroot-path /var/www/html:example.com,www.example.org --webroot-path /usr/share/nginx/html:example.net,www.example.net
```

`/var/www/html` will be used for: `example.com,www.example.com,example.org,www.example.org`
`/usr/share/nginx/html` will be used for: `example.net,www.example.net`

The details would have to be worked out. Can the start or end of the range be optional? What happens if you don't provide a range? What if two ranges overlap?

#### CLI option order matters
This is the approach proposed in #1594. Basically, you propose some kind of ordering saying that the `--webroot-path` flag applies to all domains before/after the flag that don't already have a webroot.

My problems with this approach are we've done a fair amount of work to make sure that CLI order doesn't matter. Additionally, I think this behavior is unintuitive for those familiar with *nix command lines. This doesn't mean much, but can anyone point me to a successful CLI program where the ordering of the flags (not things like subcommands/options without flags) matters?

The benefit of this approach is it's less verbose. It's reducing verbosity by imposing restrictions on command line ordering.

#### Other
Unfortunately, I haven't come up with any other approaches. You either state the mapping in a single flag (which requires duplication) or impose restrictions on command line ordering.

If anyone has any thoughts on this, I'd love to hear them.

**Comment by pde** [comment]
@bmw imagemagick's `convert` command gives flags a similar [ordering based semantics](http://www.imagemagick.org/Usage/basics/#why).

The other minimal syntax that I think is available is to use something like `--webroot-map` in a way that actually implies the domain names.  I [started implementing it](https://github.com/letsencrypt/letsencrypt/tree/webroot-map-and-flags) on top of #1594 but it's going to take a while to fix the tests, and probably JSON is the wrong way to format the dictionaries.

That could ultimately look like:

`--webroot-map {example.com,www.example.com:/var/www/example, m.eg.is,eg.is,www.eg.is:/var/www/eg}`

That's a bit of a nuisance to parse because it can't be split on `,`.  The dict entries could be separated by `;`, but then the `;` needs to be escaped.  Or the strings could be protected by `"`, as occurs in `JSON.parse`, but that's no longer really minimal.

**Comment by pde** [comment]
@grubberr may have some thoughts on this too.

**Comment by centminmod** [comment]
which ever method is used it should

1. be compatible with cli.ini so you could do something like `-c san.cli` and specify a bunch of domains in san.cli or something
2. the syntax would be easy to script/automate for in command languages like bash shell scripting etc at least.
