### ISSUE TITLE
Client should be able to accept CSR's in either PEM or DER format.

### ISSUE THREAD

**Issue by phpmypython** [letsencrypt/letsencrypt#1082]
This can be remedied most easily by using openssl to convert PEM CSR's into DER. No private key is needed for that operation. the openssl shell code to perform the operation is below
```bash
openssl req -in pemcsr.csr  -inform PEM -out dercsr.der -outform DER
```

**Comment by phpmypython** [comment]
im not familiar enough with the client to know how to implement this but i believe this is the python code that would be able to read in a PEM csr and then set a var equal to a DER csr value which can then be passed along.
```python
    pemcsr = OpenSSL.crypto.load_certificate_request(open("pemcsr.csr").read())
    dercsr = OpenSSL.crypto.dump_certificate_request(OpenSSL.crypto.FILETYPE_ASN1, pemcsr)
```

**Comment by kuba** [comment]
`le_util.CSR` should be refactored to store path and already loaded `OpenSSL.SSL.X509` object, not the contents of the file. Then `cli.py` should be updated to use `crypto_util.pyopenssl_load_certificate`, so that we decode cert as soon as possible - that function understands both PEM and DER if you read the docs.

Would you like to work on that?

**Comment by phpmypython** [comment]
should this take priority over 1076? because im trying to work on that as well. I want to get both of these done though. Keep in mind im learning python as i go through so it will take a bit for me to get it right

**Comment by kuba** [comment]
@pde, please provide advice on priority

**Comment by pde** [comment]
I'd probably do this one first but @phpmypython it's really up to you.
