### ISSUE TITLE
Failed building wheel for cryptography, cffi

### ISSUE THREAD

**Issue by william42** [letsencrypt/letsencrypt#1147]
Before installing `pkg_config` on my Arch Linux system, the program failed with the following error:

    Updating letsencrypt and virtual environment dependencies.....  Failed building wheel for cryptography
        Failed building wheel for cffi
    Command "/home/was3/.local/share/letsencrypt/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-VhSt8G/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Ecfzaq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/was3/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-VhSt8G/cffi

The program `pkg_config` should therefore be included as a dependency on Arch Linux.

**Comment by william42** [comment]
Checking --verbose output, at least one of the errors might be that Arch's libffi uses `/usr/lib/libffi-3.2.1/include` as the directory to put things in instead of `/usr/include/ffi`?  Maybe?  (cryptography just says that `gcc` failed instead of giving a more specific error even in verbose mode)

**Comment by kuba** [comment]
Seems like an upstream bug. @alex?

**Comment by reaperhulk** [comment]
The failure here is in cffi rather than cryptography (although without cffi cryptography can't install). cffi does have logic to utilize pkg_config to discover libffi pathing (see: https://bitbucket.org/cffi/cffi/src/775ead7b90d720ec80d422b6b6b159ac9ac19b48/setup.py?at=default&fileviewer=file-view-default#setup.py-16).

If this is being packaged as an OS level package (rather than a PyPI release) then I agree that pkg_config should be added as a dep for arch, as it's needed to discover the proper libffi include path.

**Comment by lvguanming** [comment]
`brew install libffi`
[and]
`pip install bcrypt`

BTW: the best way is use `virtualenv`
via: http://stackoverflow.com/questions/22875270/error-installing-bcrypt-with-pip-on-os-x-cant-find-ffi-h-libffi-is-installed
