### ISSUE TITLE
Listing certs/domains and expirations

### ISSUE THREAD

**Issue by jleclanche** [letsencrypt/letsencrypt#1150]
Is there a way, with the LE client, to list all the certs I have dealt with from the current machine?  `ls /etc/letsencrypt/live/` does it but requires root and doesn't show expirations/basic info.

**Comment by kuba** [comment]
I think @jdkasten works on that in the https://github.com/letsencrypt/letsencrypt/tree/cert_manager branch.

Other than that we don't have any built in method for listing that data. `root` will always be necessary (even with cert manager), but for expiration and other info you can use the following: `openssl x509 -in /etc/letsencrypt/live/$cert.pem -noout -text` (`-subject -enddate` instead of `-text` would show name and expiry only, `man x509` for more info).

Since this bug report is not really actionable, I'll close it for now.
