### ISSUE TITLE
Non-dev release scripts

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1185]
We currently have only dev release scripts. We need to create prod release scripts; this includes:
- different versioning scheme (`0.1.0` -> `0.2.0dev` -> `0.2.0` -> ....)
- figure out how to do the signing
- how to manage changelog
- how to manage `0.1.x` patch releases
- if we're still good with lock-step release of sub-pkgs or are we splitting repos

I think this should be marked for GA milestone, or otherwise we will have to use dev releases...

**Comment by kuba** [comment]
That also includes KGS.

**Comment by pde** [comment]
Will need airgapped signatures (we have infrastructure for those at EFF).

**Comment by erikrose** [comment]
On the subject of signing—or at least repeatability:

* PyPI does not allow package authors to change old packages, and it's not customary to delete old version.
* [Peep](https://pypi.python.org/pypi/peep/) is a tool a wrote to verify the hashes of PyPI packages before installing them. We use it to do deployments at Mozilla. It saves having to manage a vendor lib or run a private index server and protects against PyPI compromises and MITMs.
* Peep does not solve VCS-sourced dependencies completely, though GitHub ones have a nice workaround: [linking to the GitHub-generated zip of a revision](https://github.com/mozilla/dxr/blob/master/requirements.txt#L50). BitBucket [has the same workaround](https://github.com/mozilla/dxr/blob/master/requirements.txt#L47).
* If we use any git checkouts as part of our release process, we should be sure to run `git fsck` against them. At least as of a few versions ago, git didn't check hashes automatically on clone, so a compromised remote repo could just hand you whatever it wanted.

**Comment by erikrose** [comment]
Here are todos for next week's hacking session. These can become tickets if we decide to go this direction. Thoughts, @pde?

- [ ] Embed peep and add hashes of dependencies. (Maybe have individual requirements files for each package; maybe just have a big top-level one. TBD.)
- [ ] Do we need to keep the `pip install -U` of setuptools and pip? Possibly remove them. Virtualenv should give us usable versions by default: the earliest peep-compatible version of pip, 0.6.2, was included with virtualenv 1.4.4, released in January 2010.
- [ ] Either forcibly downgrade pip to <7 for peep compatibility, or fix peep.
- [ ] Replace insecure `pip install -U letsencrypt letsencrypt-apache` in letsencrypt-auto with peep. Run it against one or more requirements files from the network (either from our GitHub repo[1] or elsewhere). Sign the files for authentication, and check the signatures in letsencrypt-auto[2].
- [ ] Remove the redundant `pip install -U letsencrypt` that happens when we upgrade the nginx plugin. That's probably just a mistake.

Generally, letsencrypt-auto seems like a reasonable idea to me. We could try something fancier like [pex](https://github.com/pantsbuild/pex) from Twitter, but I don't have any personal experience with it, we'd still need something to install OS packages, and it doesn't help us do automatic upgrades.

Per IRC tonight, we'll defer to OS packaging practices for the letsencrypt client when they get around to that. In the meantime, letsencrypt-auto will be our own little self-sufficient package manager.

[1] We could branch off master, add the signatures, then move a `release` branch to that commit. Downside: the branch would never fast-forward.
[2] We'll probably need to shell out to gpg or something for this, as Python doesn't have any asymmetric crypto in the stdlib.

**Comment by kuba** [comment]
I have a feeling that the discussion above turned into something not that much related to the original issue: create `release.sh` that would replace `dev-release.sh` script, using different versioning scheme etc. `letsencrypt-auto` uses output of that script (PyPI packages).

**Comment by erikrose** [comment]
Ah, thanks, @kuba; I wasn't aware of dev-release.sh. Feel free to ignore any duplication of existing functionality in my comments. The other things I don't know, at present (and basically for my own reference), are…
* How paranoid you want to be. (I, for example, don't trust the CA system for important things.)
* How repeatable you want your release builds to be. (Do you want to trust PyPI, which entails trusting Rackspace, Fastly, and all CAs?)
* How you want people to obtain the release versions of letsencrypt

Don't feel obligated to spend time answering here unless you wish; I'm sure @pde will have the answers to these ready to hand at Thursday's hack session.

**Comment by erikrose** [comment]
Most of my work will be in letsencrypt-auto. Rough plan:

* We'll put a peep-armored reqs.txt in the tree somewhere, along with a signature of its SHA256.
* letsencrypt-auto will go figure out what the latest version of LE is (from PyPI or GH--over HTTPS to make it harder to artificially keep LE out of date) then wget that version's reqs.txt and signature off GH.
* It'll verify the sig with `openssl` (already in the bootstrap scripts and easy to airgap sigs for).
* Then it'll peep install that reqs.txt into the venv.
* Optionally, it can update letsencrypt-auto itself by somehow getting it (make a Python package to install it into venv/bin, for example) and then copying it over the current version. The file descriptor of the current version should stay valid through the end of the shell script, so we should be able to get away with that.

Pros:

* We don't need GPG (which is hard to airgap sigs for) or git.
* We install everything from our PyPI release artifacts rather than having everybody rebuild from source checkouts. This would matter more in a world where PyPI hosted Linux binary wheels and we could save the complexity of C compilation on client machines.

Accepted risks:

* We dynamically produce a requirements.txt from the latest constraint-satisfying versions of packages in release.sh. We'll verify author signatures where they exist and leave the rest up to the fates. At least it'll be repeatable. MITMs of the release machine should result in a flood of "Hey, my hashes didn't match" tickets.

**Comment by erikrose** [comment]
Subtickets:
* #1571 — Add peep and a requirements file with hashes.
* #1572 — Make letsencrypt-auto more paranoid.
* #1573 — Have the release script sign the requirements file.

**Comment by pde** [comment]
We have these now, but they will get some final tuning before being run on 0.1.1.
