### ISSUE TITLE
bootstrap/venv.sh

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1256]
As suggested multiple times before, this file should probably be included from `letsencrypt-auto` or deleted otherwise. Currently it's not used anywhere and it's not mentioned in the docs. Maintaining both `letsencrypt-auto` and `bootstrap/venv.sh` is a hassle.

**Comment by devnsec-com** [comment]
I think just simply delete the `bootstrap/venv.sh` file will do. I did a quick `grep`, didn't find anything references to this file.

**Comment by bmw** [comment]
I personally think the opposite and we should call out to `bootstrap/venv.sh`. It makes the code more modular and easier to understand. Since we are currently having `letsencrypt-auto` users clone our entire repo for OS bootstrap scripts, `letsencrypt-auto` calling out to `bootstrap/venv.sh` is not a problem. Furthermore, if we adopt either approach proposed in #1258, calling out to `bootstrap/venv.sh` will still work.
