### ISSUE TITLE
letsencrypt-auto should not require to git clone entire repo

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1258]
People are confused that running `letsencrypt-auto` from latest `master` gets them packages from PyPI and not bleeding edge.

Proof of concept for one of the solutions: https://github.com/kuba/letsencrypt/blob/auto.sh/letsencrypt-auto.sh. Thoughts? @pde, @bmw?

**Comment by bmw** [comment]
In general, I support the approach of having users download a single script instead of cloning our entire repo.

With that said, I think anyway we go about this is going to increase complexity and make it harder for our users to understand what the script is doing. The two approaches I've seen proposed so far is this and the `letsencrypt-auto` super script that includes all of the OS bootstrap scripts as well.

If we did the latter, I think the plan was we would ideally write a script that pieced together the OS bootstrap scripts and `bootstrap/venv.sh`. We could have each script be a function in the super script and just piece together the functions accordingly.

Between the two approaches, I think the large bash script is easier to understand as the user doesn't have to track down all of the scripts that were run on their system. With that said, this approach proposed here is easier for us to implement and gives us more flexibility of updating the script in the future. Neither approach is completely self updating though as the initial script the user runs (correctly) doesn't try to update itself.

Despite the extra effort involved, I personally am leaning towards a cleanly written and documented `letsencrypt-auto` script with the OS bootstrap code included. With that said, I think either of these approaches is better than having users clone our entire repo.

**Comment by bmw** [comment]
Since 0.4.0, `letsencrypt-auto` is a standalone file.
