### ISSUE TITLE
Support HTTP01 over SSL

### ISSUE THREAD

**Issue by bluecmd** [letsencrypt/letsencrypt#1343]
Hi,

We're running a mix variation of web servers and would prefer to use HTTP01 using the "webroot" authenticator. We're an HTTPS-only environment currently and not looking to change that, which offers a problem for us.

Could simple support for HTTP01 over HTTPS be added? You would need to disregard any certificate errors (allowing bootstrapping using self-signed certs etc.) on the server side I guess, but compared to HTTP that's not an issue.

**Comment by kuba** [comment]
We just recently got rid of this particular challenge over TLS because of security issues, see https://github.com/ietf-wg-acme/acme/pull/7.

**Comment by pde** [comment]
Yeah, this is a wontfix because of the default vhosts attack.  The two footnotes to that are: (1) if you serve a 301/302 redirect from port 80 the server will follow it; (2) if you have an existing cert from some CA (possibly Let's Encrypt, when it's time to renew) we could validate the cert and proceed.

**Comment by pde** [comment]
[a writeup](https://mailarchive.ietf.org/arch/msg/acme/B9vhPSMm9tcNoPrTE_LNhnt0d8U) on the problem
