### ISSUE TITLE
systemd timer

### ISSUE THREAD

**Issue by somniumAeternam** [letsencrypt/letsencrypt#1350]
Is it planned to add the support for systemd timers additionally to crontab for the renewer function?

**Comment by bmw** [comment]
This actually still an open question (see #880). With that said, due to the prevalence of `systemd`, I personally would very much like to include an option for `systemd` timers (I have `systemd` on my system, but not `cron`).

I'm closing this issue in favor of #880, but if you feel I didn't adequately answer your question, let me know and I'll reopen.
