### ISSUE TITLE
Using letsencrypt-auto --apache Fails on CentOS 7

### ISSUE THREAD

**Issue by kylebshr** [letsencrypt/letsencrypt#1446]
Hi there, 

I just got accepted into the beta, and I'm attempting to install a certificate using the instructions in the email. This is the command I'm running, and what's happening:

    $   ./letsencrypt-auto --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
    Updating letsencrypt and virtual environment dependencies.....Requirement already satisfied (use --upgrade to upgrade): ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse in /home/web/.local/share/letsencrypt/lib/python2.7/site-packages (from -r py26reqs.txt (line 1))
    ..
    Running with virtualenv: sudo /home/web/.local/share/letsencrypt/bin/letsencrypt --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
    The apache plugin is not working; there may be problems with your existing configuration.
    The error was: NoInstallationError()

I personally have no clue what's going on — while I'm tech savvy, this is above my head. Would appreciate any pointers :)

**Comment by bmw** [comment]
Our Apache plugin currently only works on Debian based systems because it relies on Debian specific executables (such as `a2enmod`) and directory layouts (such as `sites-available` and `sites-enabled`). See #788 for more info.

You are seeing this error message because our code is looking for these programs and directories. When it fails to find them, it assumes that Apache is not installed and exits.

While we are working on bringing Apache automation to more systems, I recommend you try one of our other plugins. More information is available [here](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins).

I'm closing this ticket as it is a more specific form of #788, but feel free to follow up here, the community [forum](https://community.letsencrypt.org), or #letsencrypt on Freenode if you need additional help using Let's Encrypt.
