### ISSUE TITLE
letsencrypt-auto: Install letsencrypt packages using pacman for Arch

### ISSUE THREAD

**Issue by felixonmars** [letsencrypt/letsencrypt#1510]
Hello,

I am packaging letsencrypt packages for Arch, and as a rolling release we are always following the latest letsencrypt releases. I understand that letsencrypt-auto is meant to be a script for installing into a virtualenv currently, but as more howtos and experience came out it's somewhat treated as the recommended setup now. So I would like to suggest to add the ability to use our system package manager to install letsencrypt packages (and even by default, if possible).

Thank you!

**Comment by kuba** [comment]
So, I don't think that `letsencrypt-auto` should actually install packages from `pacman` (just like it shouldn't for any other distro). However, I would suggest to drop support for Arch in `letsencrypt-auto` and simply instruct users to use `pacman` instead. Ideally, we should get rid of `letsencrypt-auto` altogether...

**Comment by felixonmars** [comment]
I see, I totally agree with you.

**Comment by pde** [comment]
Feel free to send a PR that has `letsencrypt-auto` suggest Arch packages rather than running on Arch.  If there's any risk of Arch falling behind official client releases, it should still be possible to run `letsencrypt-auto` on Arch with `--debug`.  If Arch is expected to always track upstream releases very swiftly, we could also remove Arch support from `letsencrypt-auto` altogether.
