### ISSUE TITLE
Misleading example in closed beta invite email

### ISSUE THREAD

**Issue by flingtoad** [letsencrypt/letsencrypt#1523]
One of the example the the closed beta invite email suggests using the following:
  ./letsencrypt-auto certonly -a standalone \
  -d example.com -d http://www.example.com \
  --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview

This gives an error because it can't verify the domain. It can't verify the domain because the regexp used to verify the domain doesn't consider the 'http://' in 'http://www.example.com' to be valid. The regexp is  in 'letsencrypt/configuration.py'
```
156     # FQDN checks from
157     # http://www.mkyong.com/regular-expressions/domain-name-regular-expression-example/
158     #  Characters used, domain parts < 63 chars, tld > 1 < 7 chars
159     #  first and last char is not "-"
160     fqdn = re.compile("^((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+[A-Za-z]{2,6}$")
161     if any(True for d in domains if not fqdn.match(d)):
162         raise errors.ConfigurationError("Requested domain is not a FQDN")
```
Either the regexp or the example should probably be amended.

**Comment by SuperMatt** [comment]
My email doesn't have this issue. I wonder if maybe your email client has tried to be too helpful by injecting the http:// to the url. 

  ./letsencrypt-auto certonly -a standalone \
  -d example.com -d www.example.com \
  --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview

My email was received at 22:04GMT, which is 16 hours ago -  the time that your issue was raised, so I think they would have been sent out with the same instructions. Double check the source of your email to see what it says.

**Comment by flingtoad** [comment]
The 'http://' is in the source, but it could have also been manipulated by my mail client, as you say. If nobody else is having the issue, it probably safe to assume it's my mail client.

**Comment by bmw** [comment]
I can confirm this isn't in the e-mail text and must be due to your mail client. Thanks for checking with us though @flingtoad.
