### ISSUE TITLE
Existing Certificate <Replace> or <Cancel> question should actually default to <Reinstall>

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1546]
Currently if there is an existing cert for the names you requested with `run`, you get this message:

`You have an existing certificate that contains exactly the same domains you requested (ref: /etc/letsencrypt/renewal/isnot.org.conf) Do you want to renew and replace this certificate with a newly-issued one?`

These are the wrong options.  Prior to the renewal window, the default option should be **\<Reinstall\>**.  After the typical renewal window has opened, the **\<Replace\>** default should become **\<Renew\>**.

Also we should convince ourselves that it's actually a good idea to ask these questions at all; and ensure that we have CLI flags to control the answer.

**Comment by pde** [comment]
Until we fix this, we believe that some people will make themselves many copies of the same certificate unintentionally.  So flagging this as relatively urgent amongst **nice for 1.0** milestones.

**Comment by pde** [comment]
Temporarily putting this in **1.0 for launch**, to just see if we can do it.

**Comment by bmw** [comment]
I think this issue is actually little tricky. Just to make sure everyone is on the same page including myself, this question is asked when requesting a new certificate for a subset of domains found in a lineage. This can be a strict subset or identical names to an existing lineage.

This is actually quite subtle. Imaging you have a lineage for example.com, example.org, and example.net and then run the client requesting a cert for example.com and example.org (excluding example.net). What should the client do? Should it update the existing lineage? If so, it may break a server for example.net. If it doesn't update the existing lineage, the configurations for example.com and example.net need to be updated.

With that said, I think there is value in adding some of the functionality @pde proposed above. The one choice I'm not sure I agree with is **\<Reinstall\>**. The problem is this question comes up during authentication, not installation. I believe we have correctly been trying to make `run` the equivalent of `certonly` followed by `install` (see #771). This moves in the opposite direction as allowing the user to choose **\<Reinstall\>** when running `certonly` doesn't make sense.

The one thing we might be able to do is provide something like a **\<Keep existing cert\>** option (hopefully with better wording). Probably a little early to jump into implementation details, but the way I see this working is if **\<Keep existing cert\>** is chosen, `_auth_from_domains()` in `cli.py` simply returns the existing lineage without any modification. If this is done, `certonly` will return with no further effect and `run` will give that certificate to the `installer`.

**Comment by bmw** [comment]
Given the complications in the short novel I just wrote, I think getting this done properly by Thursday is a little optimistic.

**Comment by pde** [comment]
Agree that Thursday is feeling optimistic.

**Comment by pde** [comment]
In terms of architecture, here's what I'd say: if you are landing in the **<Reinstall>** case, then `run` is just going to skip over the `auth` portion and go straight to install.  It would still be fine if run almost-literally calls `obtain_cert()` first and then `install()` second, it's just going to have some logic around the first of those calls.

**Comment by pde** [comment]
In practice we probably can't call the exact same function for `certonly` and the first step of run, but they can share a subroutine that does the actual work.

**Comment by pde** [comment]
Following discussion with @schoen: the **\<Reinstall\>** button should be present when the new cert contains names that are identical to or a subset of the preceding ones.

If the new cert contains names that are a strict superset of a preceding cert, we can leave the current UI in place.

Optimal handling of the case where the new cert contains names that are a "strict intersection" with an older one (ie all parts of the Venn diagram are non-empty) may require further UI design work and is beyond the scope of this ticket.

**Comment by pde** [comment]
Landed.

**Comment by alexweissman** [comment]
So, if I understand correctly, this new update should let me create a new cert for `www.example.com`, even if I've already hit the rate-limit for `example.com`?

**Comment by lichtamberg** [comment]
When is this going to be released? 
We have this problem too... We have subdomain for each of our customers, f.e. customer1.mydomain.com, customer2.mydomain.com, customer3.mydomain.com, ... 
And each of them has an own server and we need seperate subdomain certificates.

This service is really nice in general already, but not usable for us with this limitation!

**Comment by ssbarnea** [comment]
I can confirm that the rate limit applies to the root domain, I tried to generate a certificate for a new subdomain and I got the limit message from start.
