### ISSUE TITLE
letsencrypt-auto fails

### ISSUE THREAD

**Issue by ernstherko** [letsencrypt/letsencrypt#1587]
Python 2.4.3 (CentOS release 5.10) has no option <b>--version</b> only <b>-V</b>.

<pre># diff letsencrypt-auto .vers/letsencrypt-auto.v20151120
98c98
<   PYVER=`$LE_PYTHON -V 2>&1 | cut -d" " -f 2 | cut -d. -f1,2 | sed 's/\.//'`
---
>   PYVER=`$LE_PYTHON --version 2>&1 | cut -d" " -f 2 | cut -d. -f1,2 | sed 's/\.//'`
# </pre>

<pre># ./letsencrypt-auto 
You have an ancient version of Python entombed in your operating system...
This isn't going to work.</pre>

Ok, I need Python 2.7 :(

**Comment by bmw** [comment]
Yes. You need a newer version of Python to run Let's Encrypt. Python 2.6 is also supported, but support was more recently added and is somewhat experimental. To use it, you have to run `letsencrypt-auto` with the `--debug` flag.

Looking quickly, it appears that our Python version requirements are not documented. We should fix that. I created #1589 to track the issue. Since we have no plans of supporting Python 2.4 at this time, I'm closing this issue. Please respond if you think it should be reopened.

**Comment by ernstherko** [comment]
That's ok!

Be carful with <b>python --version</b>

<pre># python --version
Unknown option: --
Unknown option: -e
Unknown option: -r
Unknown option: -s
Unknown option: -o
Unknown option: -n
Unknown option: --
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
</pre>

<b>python -V</b> seems okay!
<pre># python -V
Python 2.4.3
</pre>
