### ISSUE TITLE
Remove Content-Type checks from http-01

### ISSUE THREAD

**Issue by ThomasLeister** [letsencrypt/letsencrypt#1595]
Hi,

I just tried to fetch certificates via manual mode with the latest version of the LE Client (at commit  ad3890d), but the process failed: "Self-verify of challenge failed, authorization abandoned."

My challenge files at .well-known/acme-challenge were set up correctly and my nginx webserver sent "text/plain" as content type. I verified that by entering the challenge URL into my Firefox web browser and analysing the headers with the integrated webdeveloper tools.

After some more research in the LE Client log I found out that the ACME server did not receive a "text/plain" header from my server, but "application/octet-stream, text/plain", which of course did not match "text/plain". Firefox only told my about "text/plain" but did not display the additional "application/octet-stream" content type. After I did this in my Nginx config:

```
location ~ /.well-known/acme-challenge/(.*) {
        default_type text/plain;
        # add_header Content-Type text/plain;
}
```

... it perfectly worked, because my Nginx just sent "text/plain" as a content type header. You might assume that adding "add_header Content-Type text/plain" to your Nginx config would do it - but it doesn't. You have to use "default_type" to get it working.

So this is my suggestion: Let the LE client check if there *exists* a "text/plain" anywhere in the Content-Type header string, not if the content type string *is exactly* text/plain. This would improve usability in my opinion and prevents users from going crazy ;)

What do you think about it?

**Comment by bmw** [comment]
This problem actually exists for historical reasons and is on its way out. The [ACME](https://github.com/ietf-wg-acme/acme) spec used to require that the content type be exactly `text/plain`. When this was true, the client behaved properly.

In the past couple weeks, this restriction has been removed from the spec and the client is in the process of being updated. Already merged into `master` is a fix so that the client will continue to pass the challenge response to `boulder` (the Let's Encrypt server) if it is unable to verify the challenge. This fix will be in place on PyPI later on today.

The client also no longer needs to verify `Content-Type` header and this check should be removed. It appears we currently don't have an issue for this problem so I'm hijacking this one. Please respond if you think there are other problems that should be addressed.
