### ISSUE TITLE
DDNS Rate Limited

### ISSUE THREAD

**Issue by SysVoid** [letsencrypt/letsencrypt#1607]
The domain ddns.net is being rate limited, which seems weird to me since it's part of a large dynamic DNS provider (no-ip.com).

```
An unexpected error occurred.
Error: rateLimited :: There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: ddns.net
Please see the logfiles in /var/log/letsencrypt for more details.
```

Can *ddns.net* be limit free?

**Comment by patf** [comment]
Rate limits are enforced on a "TLD + 1" level based on the public suffix list (including private suffixes, from how I understand the code).

Dynamic DNS providers can request to be added to this list [here](https://publicsuffix.org/submit/).

You could
 * try contacting no-ip and check if they're willing to add their domains,
 * switch to a provider already on the list (at a glance: DynDNS, probably others too),
 * or wait for GA, where rate limits will probably be relaxed a bit, and rush to get a cert :smile:

**Comment by SysVoid** [comment]
@patf I'll contact no-ip.
Thanks!

**Comment by kaefert** [comment]
Hey there! Had the same problem (for a *.no-ip.org domain) and contacted no-ip about it.
They said that they do not allow for SSL certificates to be purchased for their domain names.

They said that the SSL certificate cannot be generated since No-IP owns the domain No-IP.org. In order to issue an SSL certificate you need to be able to confirm you own the domain. Since the domain is owned by No-IP this cannot be confirmed.

So either they have no idea what I was asking for, or they don't want to allow this on purpose.

**Comment by SysVoid** [comment]
@kaefert yeah, they said the same to me.

I'm going to continue with my attempt to get the message through to them.

**Comment by marco44** [comment]
I'm off to duckdns. Luckily, there are very few users using my adress yet.

**Comment by kaefert** [comment]
@marco44 I'm not sure if this is can be a permanent solution, even if you are one of the lucky firsts of your domain.

 --> The certificates have a short live span. I think the first time the letsencrypt client tries to renew your certificate it will run into the same problem we are facing now with no-ip domains.

**Comment by marco44** [comment]
duckdns is in the publicsuffix list… I guess it should work. I will know in a few days :)

**Comment by kaefert** [comment]
@marco44 ahh! okey well then of course I guess it should work! :+1:

**Comment by Mikaela** [comment]
As a workaround, you could register your own domain and make CNAMEs from it to your dyndns.

For top level domains, only CloudFlare supports CNAMEs with their [CNAME flattening](https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root), but as they aren't registrar, you must register the domain somewhere else (I personally like [Gandi](https://gandi.net/)) and point it to them.

**Comment by noipcom** [comment]
No-IP has requested their Enhanced and Free domains be added to public suffix list in https://github.com/publicsuffix/list/pull/64

**Comment by rapiertg** [comment]
Just got this message:

"Hello,

We have added our No-IP free and Enhanced Domains to publicsuffix.org. If you have any further questions or issues please let us know."

**Comment by SysVoid** [comment]
Neat.

**Comment by Panderine** [comment]
Great news! waiting for the good to go ;)

**Comment by yookoala** [comment]
Any news on this issue? I've just checked and the rate limit is still here.

**Comment by yookoala** [comment]
For anyone who are interested:

1. letsencrypt references [public_suffix_list.dat][public_suffix_list.dat] ([Public Suffix List Project][publicsuffix]) for rate-limit exceptions.

2. noip.com domains are not in [public_suffix_list.dat][public_suffix_list.dat]. @noipcom has submitted PR [#64 Adding No-IP.com's domains to the PSL.][#64] and is yet to merge.

3. @weppos and other [publicsuffix][publicsuffix] contributors there [was discussing][#issuecomment-168995305] "what's the best way to proceed given the large amount of requests". There seems to be some progress in the discussion. The pull request has been recently updated according to [publicsuffix requests][#issuecomment-211989173].

4. We have to wait for [publicsuffix][publicsuffix] to merge that. There is nothing we can do to make it faster.

[publicsuffix]: https://github.com/publicsuffix
[public_suffix_list.dat]: https://publicsuffix.org/list/public_suffix_list.dat
[#64]: https://github.com/publicsuffix/list/pull/64
[#issuecomment-168995305]: https://github.com/publicsuffix/list/pull/64#issuecomment-168995305
[#issuecomment-211989173]: https://github.com/publicsuffix/list/pull/64#issuecomment-211989173

**Comment by yookoala** [comment]
The noip.com domains are on the public suffix list now, but when I try to issue a certificate for my no-ip.org domain, I still get the ratelimit error:

    Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: no-ip.org

What can be the problem?

**Comment by kaefert** [comment]
The letsencrypt developers will need to merge the new changes to the publix suffix list before the rate limits can reflect that.

I've looked a little bit at the code and I think it needs to be merged into this file:
https://github.com/golang/net/blob/master/publicsuffix/table.go

The latest change to that file was from this commit from March 4th:
https://github.com/letsencrypt/net/pull/10/commits/d58ca6618b994150e624f6888d871f4709db51a0

**Comment by yookoala** [comment]
Thanks @kaefert. But there will be problem in this approach.

If letsencrypt is going to just use publicsuffix from [golang/net](https://github.com/golang/net), there will be problem. According to @bradfitz in [golang/net#15518](https://github.com/golang/go/issues/15518#issuecomment-217312171), they have no intention to keep re-generating their publicsuffix frequently. That means if letsencrypt is using the exact version of publicsuffix in [golang/net](https://github.com/golang/net), it will almost never be updated.

The sensible solution would be either:
1. To generate the [table.go](https://github.com/letsencrypt/net/blob/master/publicsuffix/table.go) locally instead of using the upstream generated list.
2. To use the latest publicsuffix dynamically instead of hard-code to the source.

**Comment by yookoala** [comment]
I think the situation has changed. The problem is no longer about the publicsuffix update, but how certbot can keep up with the latest publicsuffix list. I propose to re-opened this issue and properly handle it. Thanks.

**Comment by weppos** [comment]
> The sensible solution would be either:
>
> To use the latest publicsuffix dynamically instead of hard-code to the source.

That's definitely a more flexible and maintainable approach. Unfortunately, the public suffix library built into go doesn't allow it.

That's why I created https://github.com/weppos/dnsimple-go, see #1479. @jsha is already aware of the lib, I'm open to feedback to make easier the adoption of the lib.

**Comment by patf** [comment]
> I propose to re-opened this issue and properly handle it. 

This is an issue in boulder, not certbot, which doesn't manage rate limits. https://github.com/letsencrypt/boulder/issues/1479 would be the appropriate issue for this.

**Comment by gerroon** [comment]
Can you please increase the rate limits for ddns? I have been trying to get le certs for my home server for months :( I keep hitting rate limits. I already  contacted ddns providers. SO I am out of luck, it seems like it would be much nicer if LE just limit us this way.

**Comment by yookoala** [comment]
@gerroon: I don't think LE should increase the rate limit because of this. If you read the discussions in this post carefully, DDNS are meant to be registered and would be handled differently.

If I'm not mistaken, after letsencrypt/boulder#1479, the boulder will use the live version of [publicsuffix.dat](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat) through the weppos/dnsimple-go library. So you should advice the owner of mooo.com to properly file their DDNS domains under publicsuffix list. Then LE will properly treat each subdomains in mooo.com a different domain, with separated rate limit.

**Comment by yookoala** [comment]
@gerroon: If they have doubt, please kindly suggest them to read github.com/publicsuffix#64, the relevant pull request done by No-ip for their DDNS domains.

**Comment by gerroon** [comment]
@yookoala 
Thanks for insightful reply. I will follow your recommendations.
