### ISSUE TITLE
Master should be bumped from 0.1.0dev0 to 0.2.0dev0

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1673]
This includes updating the changelog file appropriately.

**Comment by pde** [comment]
Master has been bumped to 0.1.1 (I guess it'll become 0.2.0 as soon as we land a feature :)) and the release scripts will I believe re-add "dev" if a dev release is made.

Do we need to also bump `__init__.py` in all the sub-branches now, or can we just wait until the next release, when the release script will do it for us?

**Comment by kuba** [comment]
1. It's now `0.1.0` as far as I can see, because you merged the tag with master! 9c687a2a7db3b7b3a00525fc9b0d86ca594b0ef5

2. `master` should be running `dev` at all times, not `0.1.1` (047ae326f6f901fd2c1bc1ab448248da992018c1) or `0.2`, etc.

3. Please create PRs rather than pushing to `master`, so that this kind of problems can be caught quickly. Technically speaking, we shouldn't release 0.1.1 anymore, and skip to 0.1.2 because of that error.

**Comment by kuba** [comment]
Also, I used labels to indicate which packages are affected by the problem. Did label policy change?

**Comment by jmhodges** [comment]
Please stop making changes to master until the full team is awake. We
already agreed as a team to lock down master so that we, as a team, could
respond more quickly to problems that will occur during the opening of the
Public Beta.

Peter, this behavior is irresponsible and unfair to everyone working on
this project. We need stability and peer review to make good choices and
you are undermining our work.

**Comment by kuba** [comment]
In fact `master` is broken now: `pkg_resources.DistributionNotFound: The 'acme==0.1.1' distribution was not found and is required by letsencrypt`. Users complain on IRC.

**Comment by kuba** [comment]
Fixed in 7a6e084e3ab4ae82c55acd9535d1a758985e96ec.
