### ISSUE TITLE
Got 'happy hacker fake CA' in manual mode (bug?) AND funky cli experience

### ISSUE THREAD

**Issue by 3n-mb** [letsencrypt/letsencrypt#1775]
Platform: FreeBSD, port py27-letsencrypt.

- Running: ` letsencrypt-auto certonly --manual ` I got a full chain, but it starts with 'happy hacker fake CA'. Is it expected on 5th December 2015, or should this already start with a real cert? (Stale code in port?)

- Fanky cli experience, step-by-step:
 1) Manual mode presents a direction of what should be done to server on a domain to prove, and asks to press return when done
 2) Upon pressing a return after some 20 minutes (in which time server is properly configured), a screen with color-in-cli appears showing something about error in validation, as a single line header.
 3) A few seconds later, new line appear in cli (non-gui) style, saying that everything is OK, and pointing to places with certs.
 - Given that step 3 shows success, warning display at step 2 just "puts hair on fire"

**Comment by pde** [comment]
You probably got a happy hacker cert because FreeBSD is still shipping a pre-release dev client, rather than version 0.1.0 (public beta).  Until FreeBSD ships the public beta version, you can add `--server https://acme-v01.api.letsencrypt.org` to get a valid cert.

Agreed that the manual plugin is indeed quite immature from a UI perspective.

Depending on what type of manual validation you're doing, you might like this manual client better:

http://mojzis.com/software/letsencryptshell/

**Comment by pde** [comment]
Closing this, but opening #1777.
