### ISSUE TITLE
Adding more SAN (alternative name) into existing certificate

### ISSUE THREAD

**Issue by PabloDons** [letsencrypt/letsencrypt#1853]
I know you can add alternative names to a certificate when creating it by using the "-d" option multiple times with the letsencrypt-auto script. I was woundering if it's possible to add more alternative names into an existing certificate? I have looked around and it seems nobody has an answer to that. would be greatly appreciated if you explained how to do this so I don't have to create more separate certificates as there is a limit on how many times I can do this

**Comment by schoen** [comment]
Hi @PabloDons, right now if you rerun the client and request names that are a strict superset of the names in an existing cert, you should be prompted with the ability to replace the old cert with the new cert. This uses our "certificate lineage" concept and treats the new cert as a "successor" of the old cert (which still exists). If you've referred to the old cert using any of the symlinks in `/etc/letsencrypt/live`, that link will have been updated to point at the new cert.

Technically, at the X.509 level, it's not possible to change the content of an existing cert because all certs are unique and independent and can only be issued once. However, we can have certs that are treated as related to one another by the client software (in the sense that one is regarded as a successor to another).

There is a rate limit on how frequently certs that mention the same domain names can be issued. Nothing that you can do in the client will affect this rate limit. (Choosing the behavior that I mentioned above is completely independent of the rate limit, and will not allow you to make more total changes or to make them faster than you would otherwise be allowed to.)

**Comment by schoen** [comment]
Please ask more questions if this isn't clear -- our documentation on this topic isn't great yet and it would be good for us to have a better explanation of this aspect!

**Comment by PabloDons** [comment]
Thanks @schoen for clearing this up. One more question though, what is the rate limit for how often a cert can be issued? Would be very helpful
