### ISSUE TITLE
letsencrypt inital generation does not work on ssl only site

### ISSUE THREAD

**Issue by boschkundendienst** [letsencrypt/letsencrypt#1900]
IPv4 addresses are running out, so NATting is very common.
I have a server that listens only on port 443, port 80 is used by a different server.
When I try to use letsencrypt-auto it tries to verify the server via port 80 which obviously would not work.
There should be an option that the letsencrypt-auto tool not only tries 

http://<yourdomain>/.well-known/acme-challenge/<yourchallenge>

it should also try

https://<yourdomain>/.well-known/acme-challenge/<yourchallenge>

It might be, that this is somehow possible with a parameter but I could not find it.

Keep in mind, that one might maybe upgrade his site from self-signed to a letsencrypt certificate but has only port 443 opened.

**Comment by ViolentVotan** [comment]
Ah, I just opened a ticket about what I think is the same issue as yours: #1916 

Can you confirm?

**Comment by bmw** [comment]
Unfortunately, it is required by the [ACME spec](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.2) that the initial request goes over port 80.

With that said, there are a couple workarounds for this issue. One solution is to setup a redirect from port 80 to port 443. This will enable you to complete the challenges.

Another solution is to perform `tls-sni-01` challenges instead of `http-01` challenges. The former goes over port 443. To use this approach, however, you must either:
1. Be running Apache and use the `apache` plugin.
2. Use the `standalone` plugin which needs to bind to port 443, meaning you'd have to stop your webserver.

Finally, while it won't be implemented for a few months, you may be able to use [DNS challenges](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.5) to perform domain validation in the future.

I understand thath these solutions have drawbacks, but I believe they are your best options given the current state of the ACME spec. Since this repo is for the Let's Encrypt client which is bound by the ACME spec, I'm marking this as `wontfix`. I hope my suggestions help.

**Comment by boschkundendienst** [comment]
looks similar,same problem here

via Smartphone
