### ISSUE TITLE
Mac OS X - libffi not loaded

### ISSUE THREAD

**Issue by af-bergstrom** [letsencrypt/letsencrypt#1947]
I got the following error on Mac OS10.11.2:

ImportError: dlopen(/Users/Rasmus/.local/share/letsencrypt/lib/python2.7/site-packages/_cffi_backend.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /Users/Rasmus/.local/share/letsencrypt/lib/python2.7/site-packages/_cffi_backend.so
  Reason: image not found

Solved by installing libffi with homebrew, brew install libffi 
Should perhaps be merged in to the mac bootstrap

**Comment by reaperhulk** [comment]
@af-bergstrom this was a bug in the OS X wheels for cffi 1.4.1. I accidentally built them against the homebrew libffi instead of the system libffi. I removed the wheels when I noticed (a day or two ago) but anyone with it in pip cache will continue to have the problem until a 1.4.2 is released. Sorry about that.

**Comment by af-bergstrom** [comment]
no problem for me, it was a clear error that was easily solved locally, but it's nice to hear that you have everything under control :)

**Comment by reaperhulk** [comment]
(This is now resolved with new wheels)
