### ISSUE TITLE
Cant disable properly a certificate for re-create a new ?

### ISSUE THREAD

**Issue by ImChip** [letsencrypt/letsencrypt#2037]
For delete these domaine i delete manualy files on /ets/letsencrypt/

But he isnt delete i can see my domaine certificate here https://crt.sh/?q=%25.imchip.be

I want delete 4 certificate for re-create a new for my new subdomain

Any tutoriel for that ?

**Comment by schoen** [comment]
Hi,

I suggest bringing this up on the Let's Encrypt Community Forum at

https://community.letsencrypt.org/

because it isn't specifically a client bug.

Some existing topics there that might be relevant to you:

https://community.letsencrypt.org/t/ratelimited-and-revocation/3687

https://community.letsencrypt.org/t/revoking-a-lost-certificate/5814

https://community.letsencrypt.org/t/too-many-certificates-already-issued/6481

https://community.letsencrypt.org/t/certs-deleted-and-limit/7701

https://community.letsencrypt.org/t/do-i-need-backups-of-my-certificates/5214

**Comment by ImChip** [comment]
Thank you 
i will post https://community.letsencrypt.org/t/cant-disable-properly-a-certificate-for-re-create-a-new-certificate/7852

i close this ticket
