### ISSUE TITLE
problematic integration with docker and nginx

### ISSUE THREAD

**Issue by sandys** [letsencrypt/letsencrypt#2069]
hi,
letsencrypt is awesome but because of the dependence on a running nginx for verification, it is very hard to bake it into a Dockerfile.

The problem is that my nginx configs have the paths of the cert files already built into them, but before my nginx errors out before the certs have been generated. what works brilliantly is if there is a way I can build dependence of nginx into another letsencrypt verifier - if only the port numbers didnt conflict.

What would be great is if letsencrypt would accept verification on a port other than 80 - this would mean we could run a standalone web server process (using even python), complete verification and generation of certificate and then nginx would start after the letsencrypt process would complete (this is similar to comment by on the acme-spec https://github.com/letsencrypt/acme-spec/issues/33#issuecomment-153618116). This will also mean updates will work well (because the letsencrypt process could restart itself and trigger restarts of all dependent processes).

**Comment by bmw** [comment]
Using ports other than 80 and 443 have been discussed before and many people involved in the project want this. With that said, Let's Encrypt is compliant with the [ACME protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-01) which currently doesn't allow this.

Since this is outside of the scope of the Let's Encrypt client, I'm closing this issue. Feel free to follow up at https://github.com/ietf-wg-acme/acme.
