### ISSUE TITLE
Renewal fails without the secret argument

### ISSUE THREAD

**Issue by Crazee** [letsencrypt/letsencrypt#2086]
I've got a crontab entry to renew the certs periodically but when it ran this month I got the cryptic error
```
 * Stopping web server apache2
 * 
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: sudo /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --email spiro.agnew@whitehouse.gov --agree-tos -d agnew.example.com
User chose to cancel the operation and may reinvoke the client.
 * Starting web server apache2
 * 
```
When after looking through the code found you needed a secret, undocumented option
```
--renew-by-default
```
on your "certonly" request to get it to actually work as you'd expect.

**Comment by bmw** [comment]
Despite our best efforts, automated renewal isn't truly supported at this time. Your renewal failed because `letsencrypt` client tried to prompt the user.

We're working hard to automate this process. You can read more about this issue [here](https://letsencrypt.readthedocs.org/en/latest/using.html#renewal). Since `--renew-by-default` is shown in the output of `letsencrypt --help all`, I'm closing this issue. Sorry for the inconvenience. We hope to support automated renewal here soon.

**Comment by Crazee** [comment]
Ah, well I didn't see it in the output of "letsencrypt-auto --help certonly" which was the subcommand I was using.  Does work now.
