### ISSUE TITLE
very slow startup

### ISSUE THREAD

**Issue by penn5** [letsencrypt/letsencrypt#2107]
It would probably be a good idea to give the user choice about whether to update python-venv and all the other dependencies.

**Comment by axtux** [comment]
I agree. When the user runs multiple command to renew multiple certificates, he doesn't want to check update before each command. Maybe an update cache could be good (if an update has been ran within 24h, then don't update).

**Comment by pde** [comment]
We agree this is a problem, especially on slower machines and internet connections.  @erikrose has been working on a new version of letsencrypt-auto which should fix this problem, by only performing a very lightweight new version check on each run, rather than examining and potentially upgrading many python dependencies each time.  Please try the experimental pre-release [here](https://raw.githubusercontent.com/erikrose/letsencrypt/letsencrypt-auto-release-testing-0.1.21/letsencrypt_auto/letsencrypt-auto) and let us know if it works better for you!

(It will run an artificial test upgrade the first time you run it, so you should see a comparatively slow run the first time, and then see it be faster after that).

**Comment by arjanvlek** [comment]
I can say that it took some time - but not too much - and that was on a very slow system (1.4 GHz Pentium M single core, with 1.5 GB of RAM and a standard issue 5400 RPM hard drive). All it did was run `apt-get update` and afterwards it installed a few packages, but that was the first time only.

**Comment by erikrose** [comment]
The new, faster letsencrypt-auto script is ready for testing, in case you want to give it a try: https://community.letsencrypt.org/t/help-test-the-new-letsencrypt-auto-again/9794.
