### ISSUE TITLE
Company/domain holder details in certificate

### ISSUE THREAD

**Issue by rjong** [letsencrypt/letsencrypt#2180]
Hi,

Is it possible to set some details of the website owner (name) into the certificate?

**Comment by bmw** [comment]
Currently it is not, at least not in the subject field. The Let's Encrypt server creates its own subject field containing only a common name set to one of the domains you requested.

Also, since this is an issue with the [server](https://github.com/letsencrypt/boulder), not the client, I'm closing this issue. Feel free to reopen on the server repo.
