### ISSUE TITLE
How to generate SSL cert for shared host?

### ISSUE THREAD

**Issue by ffxsam** [letsencrypt/letsencrypt#2202]
I'm on a shared hosting plan, and I can't seem to generate an SSL cert. I'm guessing it's because port 443 is already open and uses a certificate for *.asoshared.com. I get this error:

>Failed authorization procedure. mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found '*.asoshared.com, asoshared.com'

And I can't run letsencrypt on the shared host, I don't have sufficient permissions to do that. I don't see why the current certificate matters, I just need to generate my own and then upload it via cPanel.

**Comment by pde** [comment]
You may be able to use the [webroot plugin](https://letsencrypt.readthedocs.org/en/latest/using.html#webroot).

**Comment by ffxsam** [comment]
That sounds like I have to be able to run letsencrypt while ssh'd into the web server, which, as I mentioned, I can't do.

**Comment by kousu** [comment]
@ffxsam to prove to letsencrypt that you own the domain, it needs to be able to dial-back to its client running on that domain. If you can't make letsencrypt run where the domain is you can't prove you own it.

You could do this unreasonably difficult process instead:

# temporarily change your DNS to point at a server you do control, perhaps your house
# (perhaps) set up port forwards for 80 and 443 if you're behind a NAT (like, at your house)
# run letsencrypt with `certonly` (or `webroot`, but I think `certonly` is easier)
# change your DNS back and upload the certs

Renewal becomes irritating because you need to do this every three months, which means breaking your DNS every three months, which means at least a half hour and maybe a day of downtime for your domain, unless you also set up a proxy server after you get the certs. The whole point of letsencrypt is to automate that stuff away, so this method isn't really reasonable. I think there are cPanel plugins in the works for integrating letsencrypt on the remote server. Maybe you can bug your host to install them.

**Comment by ffxsam** [comment]
I was running the wrong command. My mistake. I believe I was using the `standalone` option instead of `manual`.

**Comment by kousu** [comment]
Huh? Do you have ssh access or not?

**Comment by ffxsam** [comment]
Yes, I do

**Comment by Vinsar** [comment]
On a shared host you are not root, letsencrypt needs to be run as root, but still try this
./letsencrypt-auto certonly --manual

Or https://gethttpsforfree.com

**Comment by ffxsam** [comment]
Yep, like I said, I was using the wrong command. Feel free to close this :)

**Comment by domantasg** [comment]
@ffxsam you can also use ACME PHP client and composer: http://www.hostinger.com/tutorials/ssl/how-to-install-free-ssl-from-lets-encypt-on-shared-hosting
