### ISSUE TITLE
EC2 is blacklisted?

### ISSUE THREAD

**Issue by MaxPleaner** [letsencrypt/letsencrypt#2235]
```txt
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: Name is blacklisted
```

The name is the public DNS for a EC2 box on AWS. 
Is there any way to get around this?

**Comment by pde** [comment]
Yes, EC2 is blacklisted because if we issue 3 month certs for ec2 names, people can spin them up, grab a cert, shut down the VM, and now possess a cert for someone else's hostname.

Other CAs also blacklist EC2 I believe.  This is going to be a wontfix unless Amazon (@pzb?) advises us to do otherwise.

**Comment by pde** [comment]
Probably if Amazon wanted to support browser-valid TLS to arbitrary EC2 instances without any additional DNS name, they could create an additional new namespace for instances with the property that the names would never be reused, or would not be reused within 3/12 months of instance termination.
