### ISSUE TITLE
Error trying to run ./letsencrypt-auto --help on Debian Jessie

### ISSUE THREAD

**Issue by chibill** [letsencrypt/letsencrypt#2274]
While trying to use letsencrypt for the first time on Debian Jessie I get an error. 

Here is the error. http://pastebin.com/xCLASpbn

When i run apt-get install python2.7-dev I get this error. http://pastebin.com/QuDrPKxj

when I run apt-get install on the missing package it all boils down to a problem with libc6-dev.

When I try to apt-get install that i get this. http://pastebin.com/SrxRcXk4

Which means the libc6 on my system is to new for everything else...  Any idea how to fix this?

**Comment by pde** [comment]
Is this stock Debian Jessie, or a system that's been upgraded through a series of releases?

This *looks* like a fairly typical situation with messed up debian packages due to upgrades across releases. Ask for help untangling in #debian on `irc.oftc.net`.  It's almost certainly not a problem that's specific to or caused by `letsencrypt-auto`.

We're expecting packages to land in `jessie-backports` in the next day or two, btw.

**Comment by chibill** [comment]
I upgraded from wheezy exactly as it said to on debain's site. Yeah. I guess it's a debain issue but I don't understand what could have caused the problem. Sorry to bother you.
