### ISSUE TITLE
change private key when renewing certificate?

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/letsencrypt#231]
at 31c3, the idea came up that changing the private key when renewing the certificate might be a good idea.

if private key is compromised and you need to revoke the cert(s), you'ld need to revoke *all* cerificates ever issued for that private key.

**Comment by exploide** [comment]
If this will be implemented, it should be done carefully with having HPKP in mind.

https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

**Comment by jsha** [comment]
I think the default behavior should be to use a new private key.

For HPKP, implementors are very very strongly recommended to pin a set of intermediate certificates rather than their leaf certificate, so as long as people don't do anything crazy it shouldn't be an issue.

That said, people do crazy stuff. Perhaps we could request an HTTPS URL from the server and check for HPKP before rotating private keys.

**Comment by exploide** [comment]
From my point of view, the nice thing about HPKP is that it reduces the need for trusting CAs. In the IETF draft, I didn't found a strong recommendation to pin an intermediate certificate. Instead they are talking about *a necessary trade-off between [...] pin specificity [...] and flexibility*. So if an admin really knows what he is doing - why not pin the server's key (alongside a backup key, of course).

But this is not the subject of this issue.

I particularly like your idea of requesting an HTTPS URL to figure out if there are HPKP issues when renewing certificates.

**Comment by pde** [comment]
This is actually how the client operates.  We might want to add a flag to *not* do this, but that would be another ticket...
