### ISSUE TITLE
Allow specification of --organization when creating a certificate

### ISSUE THREAD

**Issue by Crazee** [letsencrypt/letsencrypt#2317]
Allow specification of --organization that would populate the O= field of the DN.  This would make the certs a bit more user-friendly.

**Comment by schoen** [comment]
@Crazee, thanks for the suggestion. We don't have a way to verify people's assertions about what organizations operate servers, and we can't include information in the certificate that we can't verify. Letting people include unverified self-asserted information in the certificate itself is a vector for confusion for relying parties. Formally asserting which organization operates a service is a part of OV cert issuance rather than DV, and Let's Encrypt has decided to do only DV because we know how to fully automate it.

**Comment by Crazee** [comment]
One thing you could do is either compare with (or just use) the value of the "Registrant Organization" from "whois server.example.com" for their requested DNS name.  If you get no result go up a level, "whois example.com", etc.

Though you could lie to the Registrar, of course.
