### ISSUE TITLE
Preserve comments when updating renewal configs

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2368]
The approach proposed by #2361 doesn't preserve comments in renewal config files. When these files are documented, comments MUST (where MUST is defined in RFC 2119) be preserved.

**Comment by schoen** [comment]
I spoke to @bmw about this today and I think we agree that what should happen is preserving the actual `ConfigObj` object (because the underlying library tries to preserve comments already). Right we're explicitly not using the same `ConfigObj` in `save_successor`. What happens is that `save_successor` calls `update_configuration`, which in turn called `write_renewal_config`, which makes a new `configobj.ConfigObj` and calls `.write()` on it. Even this might be OK in theory but we completely replace the `[renewalparams]` second in that object, which may be the precise moment at which associated comment lines are discarded. I'll experiment with that a little more to be sure.

**Comment by schoen** [comment]
Replacing the entire `[renewalparams]` does seem to be the trouble. We could instead loop over the items in the object and store their new values if applicable, which elicits different (comment-preserving) behavior from the `ConfigObj`. We can still delete individual values with `del` if they are not to be saved, which I confirmed removes them from the underlying file without removing comments from other lines.

**Comment by schoen** [comment]
I think this looks something like

```
if "renewalparams" not in config:
    config["renewalparams"] = {}

config["renewalparams"].update(relevant_data)

for k in config["renewalparams"].keys():
    if k not in relevant_data:
        del config["renewalparams"][k]
```

This has a different effect (preserving comments) from simply saying `config["renewalparams"] = relevant_data`, as we do right now.
