### ISSUE TITLE
Running apache certonly with --vvvv dumps the complete history of all config changes

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2410]
It should only display the ones that are being made during the current run, I believe.

Eg: https://gist.github.com/pde/4e0a7b05b59185b87f3d

**Comment by SwartzCr** [comment]
this refers to #2009

**Comment by SwartzCr** [comment]
so the issue here is that view_config_changes looks at all permanently saved config changes which get saved in a directory with specifically written save_notes
in this case we want to see temp changes, in fact these changes will never be saved in such a way as to be shown in view_config_changes
instead what we will likely have to do is diff the activated apache conf file with the one that we've moved to `/var/lib/letsencrypt/temp_checkpoint/`

**Comment by pde** [comment]
Done.
