### ISSUE TITLE
"Unsupported filesystem layout. sites-available/enabled expected" Apache 2.4.10, Ubuntu 15.04

### ISSUE THREAD

**Issue by Ma-ve** [letsencrypt/letsencrypt#2426]
```
cd /opt/letsencrypt
git pull (11 feb 0:57 GMT)
./letsencrypt-auto --apache -d {domain}
```

results in:

```
root@packer-ubuntu-15-04-amd64:/opt/letsencrypt# ./letsencrypt-auto --apache -d {domain}
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --no-self-upgrade --apache -d {domain}
Unsupported filesystem layout. sites-available/enabled expected.

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/{domain}-0001/fullchain.pem. Your cert will
   expire on 2016-05-10. To obtain a new version of the certificate in
   the future, simply run Let's Encrypt again.
```

Apache 2.4.10
Ubuntu 15.04
DigitalOcean server. Other domains have worked in the past, I'm afraid of regenerating them now.

Googling the error gives no joy but 3 results, all of which are dumps of the same.

**Comment by schoen** [comment]
Hi @Ma-ve, I'm not sure about the Unsupported filesystem layout error; is it possible that you moved anything around in `/etc` compared to your operating system's original web server configuration?

With respect to getting a separate certificate lineage instead of renewing the original one, is it possible that you had any other subjectAltNames as a part of that cert, such as `www.domain`? Currently in order to tell the client that you want to renew an existing cert and replace the symlinks in `live`, you need to specify *each and every name* that's a part of the original cert, so if the original covers `www.domain` as well as `domain`, you would have to say `-d www.domain -d domain`; otherwise the client asks for a cert that only covers `domain`, which is not regarded as a potential successor to the pre-existing larger/more-inclusive certificate.

To put this another way, `-d` is used to specify the complete contents of certs, currently not as a means of selecting or directly referring to a pre-existing cert that may cover that domain among others.

**Comment by Ma-ve** [comment]
Thanks @schoen for the quick reply! Sadly, this is a new domain, so none of those apply I'm afraid. Both `-d {domain} -d {www.domain}` and `-d {domain}` do not work. 

I haven't moved anything in the `/etc` folder: Apache is still in `/etc/apache2`, there's an `/etc/letsencrypt` folder which contains:

```
drwx------  accounts
drwx------  archive
drwxr-xr-x  csr
drwx------  keys
drwx------  live
-rw-r--r-- options-ssl-apache.conf
drwxr-xr-x renewal
```
I don't think I've made any changes to my file system.

**Comment by Ma-ve** [comment]
I've found out what the problem was: someone (me) put the domain in `/etc/apache2/conf-available` and did `a2enconf domain`, rather than put it in `/etc/apache2/sites-available` and go with `a2ensite`. It works now. Thanks!
