### ISSUE TITLE
how to remove apache plugin

### ISSUE THREAD

**Issue by Se7endAY** [letsencrypt/letsencrypt#2595]
how to remove apache plugin?

**Comment by schoen** [comment]
Hi @Se7endAY, I don't really understand what you want to do. The Apache plugin is a built-in part of the Let's Encrypt software, but you don't have to use it if you don't want to (for example, you can use `webroot` by specifying `-a webroot`).

**Comment by chludwig** [comment]
It's quite an old question, so here an old answer first, followed by a new one:

When using `certbot-auto` you can simply delete the files with:  
```
sudo rm -R /opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache*
```
what I did all the time with success,
or by using pip to uninstall it:  
```
sudo /opt/eff.org/certbot/venv/bin/pip2.7 uninstall certbot_apache
```

When using the latest version with snap, the folders change and are protected against deletion, su unfortunately neither
```
sudo /snap/certbot/current/bin/python3 -m pip uninstall certbot_apache
```
nor 
```
sudo rm -R /snap/certbot/current/lib/python3.8/site-packages/certbot_apache*
```
are bringing success and are ending in some errors because of `Read-only file system`. So when using Snap, it seems to be impossible to uninstall the plugin.
