### ISSUE TITLE
Ensure auto-update URLs are unbroken by rename

### ISSUE THREAD

**Issue by SwartzCr** [letsencrypt/letsencrypt#2639]
When we move the repo from LE/LE it's likely that certain things that rely on the github.com url will get broken, we need to make sure this doesn't happen.
Presumably this will involve re-directs or editing things like the LE Auto script. This needs to be decided and could get tricky if sub-directories change names (i.e. things besides just the repo name change)
this is linked to #2638

**Comment by SwartzCr** [comment]
@erikrose do you want to be in charge of this?

**Comment by pde** [comment]
Can we get a renamed repo to play with?  Then we can tell what kinds of redirects github will serve, and test leauto against it.

**Comment by erikrose** [comment]
@SwartzCr I'm going to be time-limited for the forseeable future, so it's best not to block this on me. Happy to answer questions, though.

**Comment by SwartzCr** [comment]
@erikrose I assume you haven't tested this and don't have time to?
@bmw do you think you could test this as part of your LE-auto re-writing?

**Comment by bmw** [comment]
Yes, I can take this.

**Comment by bmw** [comment]
Changing the name/location of files/directories within our repo will break URLs. For instance, URLs to files inside of `letsencrypt`, `letsencrypt-apache`, etc. in `master` are now broken. However, these files aren't used for updates.

The only paths we care about here are `letsencrypt-auto`, `letsencrypt-auto-source/letsencrypt-auto`, and `letsencrypt-auto-source/letsencrypt-auto.sig`. All other paths can be changed.

I tested the code that is used to fetch new copies of `letsencrypt-auto` using https://github.com/swartzcr/testrepo. I was happy to find that when accessing the raw contents of files, GitHub doesn't redirect you, it simply serves the file contents, even if they have changed since the rename. For example, https://raw.githubusercontent.com/swartzcr/testrepo/master/amul/amul was modified after the rename, but the GitHub serves the files contents with no redirect.

With this in mind, we have to make sure we don't modify the paths to the three files listed above, but other than making sure we don't do that, I think this issue can be closed.
