### ISSUE TITLE
_set_by_cli spuriously flags all plugin variables to be set by cli

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2651]
In new code intended to fix #2503, I use `_set_by_cli` as one criterion for deciding to save something in the renewal config file. I found that it sometimes returns `True`, resulting in saving items, even when I did not actually set those things from the CLI at all. The items in question that I observed so far were these:

```
apache_enmod = a2enmod
apache_server_root = /etc/apache2
apache_dismod = a2dismod
apache_handle_sites = True
apache_handle_modules = True
standalone_supported_challenges = "tls-sni-01,http-01"
apache_le_vhost_ext = -le-ssl.conf
apache_challenge_location = /etc/apache2
nginx_server_root = /etc/nginx
nginx_ctl = nginx
apache_vhost_root = /etc/apache2/sites-available
```

There could be others, but these were ones I saw so far.

Cc @pde

**Comment by pde** [comment]
Noah expressed interest in this...

**Comment by SwartzCr** [comment]
The issue is that plugin_arguments get added through a call to `add_plugin_args` which in turn pulls plugin parsers from `six` and calls `add_argument`
This presents a few problems.

1. The `modify_arg_for_default_detection` line is in HelpfulArgParser's `add` command, not in `add_argument`
2. The parsers used for this are `SilentParsers` not helpful
3. These parsers don't necessarily have detect_default set

it'd be nice to have SilentParser have the same implementation of HelpfulArgParses modify_arg_for_default_detection, and then we could add a detect_default flag to it before adding plugin args - that would solve this problem

**Comment by bmw** [comment]
I'm going to take this.
