### ISSUE TITLE
Renewer needs to reload webserver. 

### ISSUE THREAD

**Issue by plutocrat** [letsencrypt/letsencrypt#2676]
Hi, 
I just noticed my certs had renewed successfully, but the old certs were still showing on the website. This was not a big deal immediately, but after 29 days they would have expired, and that would cause problems. 
So, for a fully automated solution, the letsencrypt renew command should reload the webserver config. In my case this was a matter of 'service nginx reload' and the new certs appeared. This command should only be run on a successful renewal. i.e. when the cert has less than 30 days to run. 
Perhaps this could be addressed by a line in the relevant /etc/letsencrypt/renew/domain.conf file. Something like
run_on_successful_renewal = 'service nginx reload'

**Comment by nitmir** [comment]
Having a `run_on_successful_renewal ` option would be nice. It could also allow for automatic TLSA record publishing.
```
run_on_successful_renewal = 'publish_tlsa; sleep 3600; service nginx reload'
```

**Comment by FelixSchwarz** [comment]
I like the approach with a generic command being executed. This also helps for more complex setups where you probably just want to "register" the task ("restarting webserver") so these can be processed during the regular maintenance windows.

**Comment by osirisinferi** [comment]
@nitmir: Shouldn't you also add a old-TLSA-record removal command after the `sleep`?

**Comment by nitmir** [comment]
@osirisinferi  in fact my script (`make_tlsa`) scan certificates on 3 hosts, generate records pour every valid certificate (event old one in `/etc/letsencrypt/archives`) and SSFP records for every ssh pub key in `/etc/ssh/` in a file by dns zone. This files are included in bind dns zones files(`$INCLUDE /etc/bind/generated/db.tlsa.example.com example.com.`). So just calling `make_tlsa` will add and removes records, update the dns serial and reload the dns zones if needed.

Old certificates get remove then they are expired (`make_tlsa` is also called on a daily basis).

But it was just an example.

**Comment by pde** [comment]
The current plan for this is via #2331, where I'm basically planning to make the "callback in case of renewal" be a function that's defined in a script in /etc.  It'll be like the [second of these two scripts](https://letsencrypt.org/getting-started/#writing-your-own-renewal-script), but will grep for [this message](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L714) in the client's output, and call a renewal function in that case. 

The reason we're planning to grep for client output rather than having the python code call a script supplied on the commandline is that it saves us from confronting the fact that `sudo` modifies the user's PATH setting and may therefore sometimes make it hard/confusing to supply a script as a command line argument.

If there are strong reasons to have this be something that's passed in via the command line instead, let's discuss, but otherwise I'm going to mark this as "won't fix" / solved by #2331.

**Comment by pde** [comment]
And if we did do this as along the lines suggested by @nitmir we'd have to pick between these three paths:

1. Invoke the supplied command with `Popen(..., shell=True, ...)`, which allows people to do semicolon delimitation like `'publish_tlsa; sleep 3600; service nginx reload'` but makes 2 below impossible.
2. Try to check whether the command is in the PATH first, and provide a helpful error in case PATH mangling produced a problem.  But that requires us to know what the command being executed is, which is not sane if it's being parsed by the shell and can contain `;`, `&&`, etc.
3. Don't help the user with PATH problems at runtime, but print the PATH seen by the client in the output for `run_on_successful_renewal`
3. Modify our [invocation of the client](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-auto#L1674) in `letsencrypt-auto` to preserve the entire environment or just PATH.  Preserving the whole environment is easy (sudo has a flag for it); preserving PATH is hard to do safely.  The consequences of letting environment variables in to the client are unknown.  There might be no security problem, but it still makes us slightly nervous.  Also users of packaged variants of the client who call `sudo letsencrypt` rather than `letsencrypt-auto` will have to figure this out for themselves...

**Comment by FelixSchwarz** [comment]
@pde: Not sure if I really like that solution but on the other hand I will trust your judgment in the end. However one of the good things of systemd for me was the removal of shell scripts in /etc. These could be changed by the administrator but then this was also a recipe for problems when it comes to upgrades. I don't want to go there again.

Also grepping output seems really just like a band-aid (how do you ensure that "deploy cert" in your log file is actually a recent event and not one which happened months ago?). Having a proper hook looks much nicer to me and it exposes fewer internal details (the shell script itself, logging path). Also running a script regularly is just unnecessary when letsencrypt knows exactly when the event happens. And last but not least there is is a much bigger delay with a separat script.

If you are concerned about different paths you could just require an absolute path for the setting.

**Comment by pde** [comment]
I shied away from this because [these cases](https://github.com/letsencrypt/letsencrypt/issues/2676#issuecomment-198083304) felt horrible.  I'm a little torn though.  On one hand, you can say the PATH issues are a corner case.  On the other hand, I find working with situations like cron jobs where PATH is set to some limited systemwide default to be a recipe for frustrating and mysterious errors.

It's particularly bad if this is something that will only be discovered once renewal is actually happening, typically 2 months after the admin set things up.  Which makes me think that option 1 (`shell=True`) above is bad, and if we supply the command on the CLI it should be parseable by the client.  And then you have to figure out a bunch of syntax for it: `find`'s  `-exec` flag is an example but it's also kind of terrible.

**Comment by FelixSchwarz** [comment]
just my 2 ¢: I would not support arbitrary shell commands. If someone needs that (s)he should write a custom shell script IMHO. Why do you want to check the PATH beforehand at all? Just try to execute it and catch the exception if it happens. Bonus points for catching `OSError(2, 'No such file or directory')` and printing something helpful in this special case.

**Comment by pde** [comment]
Working on this today. If we proceed with command line flags for `--pre-renewals-hook` and  `--post-renewals-hook` (I actually think we only need two hooks, not three: standalone users don't need to stop their servers unless something is actually being renewed), I think this might be the most usable of all the imperfect options:

* Use `shell=True`.  That allows people to supply `--post-renewals-hook "/etc/init.d/server reload"` or `--pre-renewals-hook "service nginx stop"` etc rather than having to write a script just because their command inherently requires arguments.
* Hackishly attempt to error out early if there is a PATH problem.  That can be accomplished by `split`ting the hook command and checking that the leftmost portion is in the PATH.  Though that can be wrong in crazy theoretical ways (commands whose names contain escaped spaces?) I think it's close enough to correct that it's safe to use.

**Comment by pde** [comment]
We will also need to implement `--quiet` if this is our strategy for cron job deployment, without any wrapper script.
