### ISSUE TITLE
Which way is the best to update LetsEncrypt?

### ISSUE THREAD

**Issue by littleguga** [letsencrypt/letsencrypt#2688]
Just pull files from git?
Or something else?

**Comment by bmw** [comment]
It depends how you install it. We have OS packages available for a number of systems and if they're available, we recommend you use those. Most (all?) are being updated in a timely manner.

If OS packages are not available on your system, we recommend you use `letsencrypt-auto` as described in the [documentation](https://letsencrypt.readthedocs.org/en/latest/using.html#letsencrypt-auto). The script securely updates itself and `letsencrypt` every time it's run if updates are available.

**Comment by littleguga** [comment]
@bmw hmm. I installed from git(git clone), when I run ./letsencrypt-auto after certificates update all files in Let's Encrypt directory are not updated(`ls -al` still showing 4 January as edit date)

**Comment by bmw** [comment]
If you're using `letsencrypt-auto`, you don't need any of the other files from our `git` repo. As you have seen, `letsencrypt-auto` doesn't use them.

Instead, `letsencrypt` is installed in `${XDG_DATA_HOME:-~/.local/share}/letsencrypt` (`$XDG_DATA_HOME/letsencrypt` if you have the variable set, otherwise `~/.local/share/letsencrypt`). If updates are available, this is the copy that will be updated when `letsencrypt-auto` runs.
