### ISSUE TITLE
letsencrypt-apache on Gentoo should read /etc/conf.d/apache

### ISSUE THREAD

**Issue by LeCoyote** [letsencrypt/letsencrypt#2701]
In Gentoo, Define's are passed by the initscript as -D arguments read in /etc/conf.d/apache

LE seems to ignore that. As a result, since the "Listen 443" directive is inside IfDefine blocks, it is systematically overlooked by LE since it doesn't know about the active Define directives.

LE will therefore add a "Listen 443" temporary directive, which will cause apache to fail with a "could not bind to address 0.0.0.0:443" error. LE in turn will fail with "urn:acme:error:connection" since apache is not running during the challenge.

**Comment by joohoi** [comment]
Yeah, you are right. Gentoo is a bit of a special snowflake regarding the Apache Defines. I'd like to ping @osirisinferi for insight on this issue, as we've had some discussions about this exact thing in the past.

I'll start looking into remedying this.

**Comment by osirisinferi** [comment]
My local solution was removing the `IfDefine` blocks for `mod_ssl.so` in `httpd.conf`. Ofcourse, that's not a permanent solution for Apache on Gentoo, but at least the LE client will work.

As for a more permanent solution, that's probably going to cost some time and code. As far as I remember, in the previous issue the conclusion was a sort of `wont-fix`, because it's a single distribution with probably a disproportionate amount of effort to fix it.

**Comment by joohoi** [comment]
I might have something this time, and I've begun to implement it. Going to run some tests tomorrow and we'll see how we'll fare.

**Comment by osirisinferi** [comment]
I'd be happy to test too!

**Comment by joohoi** [comment]
I was halfway fixing this the hard way when I stumbled upon the correct Gentoo way of doing it.

#2707 should take care of this issue.
