### ISSUE TITLE
Invalid "Let's Encrypt certificate expiration notice" e-mail?

### ISSUE THREAD

**Issue by jarmo** [letsencrypt/letsencrypt#2705]
I'm receiving e-mails from Let's Encrypt about my certificates which are about to expire. In reality I've renewed these certificates some time ago already through Let's Encrypt and they're not about to expire.

Maybe something wrong with the e-mail sending logic?

(I've gotten this e-mail to all domain names owned by me and used with Let's Encrypt, for example [rand-flickr.com](https://rand-flickr.com))

**Comment by schoen** [comment]
This is a known problem (https://github.com/letsencrypt/boulder/issues/1346) but I understand it's been fixed for newer certs but not yet for older ones. I think this problem is going to be fully fixed, but is also self-limiting; you shouldn't receive this reminder incorrectly for the next round of renewals. Sorry for the inconvenience.
