### ISSUE TITLE
ACME challenge using tomcat 7

### ISSUE THREAD

**Issue by anniepaul** [letsencrypt/letsencrypt#2706]
Hi,

Can you please list the steps needed when it asks to create a new file under the tomcat server that is responding to the hostname and path given the following characteristics....

Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler manual
== Manual Challenge Handler - HTTP ==
  * Handle Time:      [1/12/2016 1:16:34 PM]
  * Challenge Token:  [2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0]
To complete this Challenge please create a new file
under the server that is responding to the hostname
and path given with the following characteristics:
  * HTTP URL:     [http://myserver.example.com/.well-known/acme-challenge/2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0]
  * File Path:    [.well-known/acme-challenge/2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0]
  * File Content: [2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0.H3URk7qFUvhyYzqJySfc9eM25RTDN7bN4pwil37Rgms]
  * MIME Type:    [text/plain]

Thanks
Annie

**Comment by schoen** [comment]
Hi @anniepaul, it wants the string listed in "file content" to be served by your server in response to a request sent to http://myserver.example.com/.well-known/acme-challenge/2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0 by the CA.

This would normally mean putting that text in a file called `2yRd04TwqiZTh6TWLZ1azL15QIOGaiRmx8MjAoA5QH0` inside `.well-known/acme-challenge` inside your web server's document root (or "web root"), wherever that is on your system.

If that doesn't work, you might want to look at whether there's something you have to change in your configuration to allow `.well-known` URLs to be served at all (some web servers have defaults that inhibit this). It would probably be more helpful to ask on the Let's Encrypt Community Forum at https://community.letsencrypt.org/ because there may be other people who have the same kind of question there.

Thanks!
