### ISSUE TITLE
Please extend documentation about domain-validated certs and extended validation certs.

### ISSUE THREAD

**Issue by dnozay** [letsencrypt/letsencrypt#2732]
> `letsencrypt`, finally a way to automate getting certificates.

That is great news for the **developers** of a website. This is also good news somehow for users whose connections will be more secure from eavesdropping and tampering. However there is still a problem that it may shift the perception about what the user thinks of a website they may navigate to.

e.g. there is a difference between `www.example.org` and `www.exāmple.org`

Before `letsencrypt`, it may have been harder for an attacker to obtain a certificate for `exāmple.org` just because of the "not-automated" part. Now that an attacker can just bring that site up, and obtain a certificate for it in an automated fashion; an unsuspecting user may fall prey to attacks because they couldn't tell it wasn't safe (aka. **poor user trusted their browser's padlock icon**).

Extended validation certs involve a human and many more checks.
https://en.wikipedia.org/wiki/Extended_Validation_Certificate

I believe it would help if the difference between domain validation and extended validation was explained in https://letsencrypt.org/how-it-works/.

e.g.

![image](https://cloud.githubusercontent.com/assets/205466/14159261/b6be1086-f689-11e5-88c7-009fe7f1178b.png)

vs

![image](https://cloud.githubusercontent.com/assets/205466/14159268/c3afd7ac-f689-11e5-87ab-0bb5810e839e.png)

**Comment by schoen** [comment]
Hi,

Right now Let's Encrypt would never issue for `www.exāmple.org` because we don't issue for any IDN names.

https://github.com/letsencrypt/boulder/issues/597

We have had a lot of discussions on our forums about the general issue of whether users may think that the padlock means that the site is non-malicious or has been vetted in some way. We hope HTTPS will come to be used for all web sites all the time, so we don't think it can or should ultimately be regarded as a signal that a site is not malicious.

If there's something we can do to try to improve users' understanding of this issue, I think that would be great, but I'm not sure the "How it Works" page is a helpful place to try to go into this (I think that page is overwhelmingly read by prospective certificate subscribers rather than prospective certificate relying parties).

**Comment by schoen** [comment]
I'm going to close this issue here because this issue tracker is meant for problems with the Let's Encrypt Python client software, not the web site. I think the best place to discuss web site content issues is generally the Let's Encrypt Community Forum at https://community.letsencrypt.org/.  Thanks.

**Comment by nitmir** [comment]
@dnozay DV certificate issuance are for long automated on the CA side. Id est, the CA just send you a email to a well known email address (like postmaster@exāmple.org) and you prove domain ownership by submitting a token received by mail. The manual action is on the side of the client, not the CA.

That was added by letsencrypt, is automation also on the client side.
