### ISSUE TITLE
Determine if *-auto should be a symlink

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#2877]
Unfortunately, the way that GitHub handles symlinks isn't ideal for `*-auto`. For example, here's a [symlink to a directory](https://github.com/certbot/testrepo2/blob/master/amul2). Symlinks to files are treated the same way. The raw contents of the symlink is simply the target's path, not the contents.

With this in mind I propose we leave `letsencrypt-auto-source` largely unmodified. Moving this directory or making it a symlink to `certbot-auto-source` will break `letsencrypt-auto`. I also think keeping both `letsencrypt-auto` and `certbot-auto` in the `letsencrypt-auto-source` directory is unnecessary as they will be the same file. This means both `certbot-auto` and `letsencrypt-auto` will be downloading `letsencrypt-auto-source/letsencrypt-auto` for updates, but this is an implementation detail and not a big deal in my opinion.

The other question we have to consider is about `*-auto`s in the root of our repo. `letsencrypt-auto` must remain in our repo in some form. All of our installation instructions use it and have done so since the beginning of public beta.

Do we want a `certbot-auto` in the root of our repo? I think we do as having `letsencrypt-auto` be the only `-auto` script in our repo when `certbot-auto` is the preferred form is a bit awkward. We could make one of the scripts a symlink to the other. The problem is this breaks anyone doing `wget https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto` (or with `certbot-auto`). While I haven't seen anyone do this, we can avoid this potential problem by having full copies of both `certbot-auto` and `letsencrypt-auto` in the root directory. I think I prefer this approach over using symlinks.

Thoughts?

**Comment by SwartzCr** [comment]
There was some discussion on the call today about whether we should include two scripts or to just have a symlink from le-auto to cb-auto. The concern is that this would break things for people who wget le-auto and try to run it.
I don't think anyone has scripted LE to work this way, and I'm mildly in favor of it because it means that people who are following old documentation will know that they've done something wrong when they wget le-auto and don't get a file back - especially since we'll no longer be telling people to wget the le-auto script.

**Comment by SwartzCr** [comment]
maybe @pde should give input as well

**Comment by SwartzCr** [comment]
We have decided to ship two identical files

**Comment by bmw** [comment]
I'll make a PR that copies `certbot-auto` to the root of the tree during the release.
