### ISSUE TITLE
constant certificate path 

### ISSUE THREAD

**Issue by hryamzik** [letsencrypt/letsencrypt#2919]
I'm trying to fix paths to certificates with ```--cert-path``` but can't get them to work. Let's say I create a certificate with:

```sh
/opt/letsencrypt/letsencrypt-auto certonly --agree-tos --redirect --duplicate --text --email example@gmail.com \
-d example.net --renew-by-default 
```

It predictively goes to ```/etc/letsencrypt/live/example.com```. Now I realise I've missed ```www.``` and try to update it:

```sh
/opt/letsencrypt/letsencrypt-auto certonly --agree-tos --redirect --duplicate --text --email example@gmail.com \
-d example.net -d www.example.net  --renew-by-default \
```

It creates a new directory. Even if I specify paths:

```sh
/opt/letsencrypt/letsencrypt-auto certonly --agree-tos --redirect --duplicate --text --email example@gmail.com \
-d example.net -d www.example.com --renew-by-default \
--cert-path /etc/letsencrypt/live/example.com/cert.pem \
--chain-path /etc/letsencrypt/live/example.com/chain.pem \
--fullchain-path /etc/letsencrypt/live/example.com/fullchain.pem \
--key-path /etc/letsencrypt/live/example.com/privkey.pem
```

Is it possible to keep the path? Might be related to #1505.

**Comment by bmw** [comment]
Actually, the problem here is the use of `--duplicate` on the command line. From the help output:
```
  --duplicate           Allow making a certificate lineage that duplicates an
                        existing one (both can be renewed in parallel)
                        (default: False)
```
While perhaps the wording can be improved, duplicating a certificate lineage refers to creating new directories in `/etc/letsencrypt/live` and `/etc/letsencrypt/archive`. In fact, new directories will be created even if you're requesting the exact same domain names.

Removing `--duplicate` from the command line and adding `www.` as in you're example, you should see a prompt like:
```
-------------------------------------------------------------------------------
You have an existing certificate that contains a portion of the domains you
requested (ref: /etc/letsencrypt/renewal/example.com.conf)

It contains these names: example.com

You requested these names for the new certificate: example.com,
www.example.com.

Do you want to expand and replace this existing certificate with the new
certificate?
-------------------------------------------------------------------------------
(E)xpand/(C)ancel: 
```
You can use `--expand` to automate this choice and always opt to expand an existing certificate instead of creating a new one.

**Comment by hryamzik** [comment]
That makes sense, thanks!
