### ISSUE TITLE
Segmentation fault on FreeBSD 10.1

### ISSUE THREAD

**Issue by slicer69** [letsencrypt/letsencrypt#294]
When running Lets Encrypt on FreeBSD 10.1 (64-bit), the following error is displayed:

```
# letsencrypt -d myhost.com

Generating key (2048 bits):
/etc/letsencrypt/keys/0001_key_letsencrypt.pem
Performing the following challenges:
   DVSNI challenge for mydomain.com

Segmentation fault
```

I will be happy to perform trouble shooting or tests to provide further information.

**Comment by schoen** [comment]
The segmentation fault must have been a result of the native code bindings via Swig, like in PyOpenSSL or M2Crypto, since an error in Python code would produce a Python traceback instead.

A good first step could be to put some debug print statements in to try to isolate exactly where the segmentation fault happens. Are you comfortable doing that? Do you need some suggestions for useful places where they might go?

**Comment by slicer69** [comment]
I'll happily insert some error checking print statements. Some hints as to a good place to start would be greatly appreciated. I'm passibly familiar with Python in general, but I haven't become with the source code for this particular project yet.

**Comment by schoen** [comment]
One first approach might be to put debug print statements in the functions in `crypto_util.py`, which is where most of the calls into the cryptographic library bindings happen.

**Comment by schoen** [comment]
My guess is that the problem is related to some stuff that will turn out to be non-portable in some part of the M2Crypto or PyOpenSSL Swig code (maybe they call into `libc` and the function prototype is different from Linux to FreeBSD?). Perhaps it's a function that isn't very widely used, so maybe the rest of those packages work properly on FreeBSD except for one particular function.

We'll find out! :-)

**Comment by thorerik** [comment]
I've tried tracing this for a bit now(sadly don't have time to try more at the moment), it seems to stop with either of these two call:
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/auth_handler.py#L166-170

**Comment by jdkasten** [comment]
I am guessing you are running the standalone-authenticator.  If you didn't select anything, you are running standalone.  (I wouldn't expect Apache to work or rather be recognized by the system.  It would take some special configuration editing and there are still some Debian specific things.) 

The standalone-authenticator (letsencrypt/client/plugins/standalone/authenticator.py) would be worth investigating.  @schoen might know what could be breaking.

PS: I am working on a major Apache update to make it more stable/easier to port, but keep on getting preempted with other tasks.

**Comment by kuba** [comment]
This can be closed now.
