### ISSUE TITLE
Having a way to e-mail user about certificate status, renewal, etc.

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#321]
We've talked about this a bit. We sometimes want to tell the user about things that have happened that relate to a certificate: for example, the fact that it's about to expire, will be renewed automatically, has been renewed automatically, will be installed automatically, has been installed automatically, has been revoked, could not be renewed, or could not be installed.

@pde suggested not using the recovery contact information to send such notifications from the CA side, but I don't think we've definitively decided whether the CA side can ever send automated e-mail to anyone about certificates. The client can definitely *try*, and it will definitely try, but it's in a worse position in terms of likelihood of success: it may not be able to send mail to `root@localhost` at all, and even if it does so, there may be no one reading that e-mail!

What's the best way to handle all of these things? I wanted to wrap `/usr/sbin/sendmail` (haven't found a convenient and maintained library for doing so); is speaking SMTP to `localhost:25` (say via Python's `smtplib`) as likely to work, more likely to work, or less likely to work?

Should we default to trying to e-mail `webmaster@example.com` on top of `root@localhost`? Or `webmaster@localhost`? (We can have an optional configuration file parameter for e-mail addresses to notify, but I don't expect it to be prompted for during the original cert deployment process, and most people won't have set it subsequently.)

**Comment by diracdeltas** [comment]
From a security perspective, it definitely seems like the CA should send notifications so people know when new certificates have been issued for their domains (that they perhaps haven't authorized).

**Comment by schoen** [comment]
@diracdeltas I'd like to see that for issuance, if possible (at least contacting webmaster and ideally also the contacts from whois). In this case, I'm especially worried about what happens around expiry and renewal, which raise less of a concern about unauthorized certs, and more of a concern about stuff that was working OK before unexpectedly breaking.

**Comment by rolandshoemaker** [comment]
It's extremely hit or miss if we'll be able to either send mail user or if they will ever even check that account, as @schoen points out.

It might be a good idea for the client to explicitly point this out to the user when run the client in a way that would later generate emails, and perhaps provide certain command line configuration options that would allow them to fine tune this (ie `--email-to`, `--email-bin` to use to other mail transport agents than `sendmail` such as `esmtp` or something). It seems a local SMTP server is much less common, while almost all systems have at least some MTA installed by default that should be able to deliver mail to local users (or to remote servers depending on how the user has configured their MTA...)

**Comment by mvdkleijn** [comment]
I'm just an interested bystander of sorts, but if I might make a suggestion on this as I do sysadmin work...

1. Change "email" into "notify". Not everyone (wants) to use email. Besides, most email is still plain text.
2. Allow for multiple methods of notifications. Even if you can only select a single channel, at least allow for more than just email. (plugins?)
3. Whatever is chosen, it should be fire-and-forget type notifications from the client perspective.
4. Allow the server admin (who sets up the client in the first place) to select the target of the notification without picking a field from the certificate.

Personally I'd love for my letsencrypt client to send me info through an Android client. Possibly something like pushbullet or notifymyandroid. This kind of setup would probably be easier to use for the client anyway. (just an API call)

And I would definitely let the client do the work, not the CA server. Since its the client initiating changes on the server it is responsible. Let the responsible party communicate.

Again, just a "bystander" so feel free to ignore my comments.
