### ISSUE TITLE
support for nginx

### ISSUE THREAD

**Issue by golodhrim** [letsencrypt/letsencrypt#36]
Hi guys,

is there a planned support also for nginx to generate the config, or to include the tool into nginx? Can one help on any part making it work for nginx, if so, let me know which file/s need to be altered for that aim to be fulfilled.

Greetins
Martin

**Comment by ThomasWaldmann** [comment]
was there any progress on this?

**Comment by aychedee** [comment]
I spent some time in December looking through the Augeas lenses but ended up but gave up before I managed to get a working ML environment.

**Comment by ThomasWaldmann** [comment]
see #200 - that might become a solution until there is specific support code for nginx.

**Comment by diracdeltas** [comment]
Heya, apparently I'm picking up this ticket. What I've learned so far is:

* The augeas lens for nginx is wildly insufficient right now. It only checks /etc/nginx/nginx.conf and /usr/portage/www-servers/nginx/files/nginx.conf, and it will fail to parse files that contain blocks nested with depth > 1.
* Writing your own lens seems somewhat complicated [1], and I haven't figured out how to tell the Python augeas wrapper to use a custom lens.
* There is a nice, 100-line MIT-licensed python module to parse/write nginx configs [2] that has some bugs but is way better than the Augeas lens. IMO the best approach is to fork this and either include it in letsencrypt or a separate repo.

[1] https://github.com/hercules-team/augeas/wiki/Creating-a-lens-step-by-step
[2] https://github.com/fatiherikli/nginxparser

**Comment by pde** [comment]
A 100 line script sounds too small to be worth suffering the pain of <tt>git submodule</tt>.  So perhaps whould just put it in our tree, and then politely send any changes we make back upstream...

**Comment by jdkasten** [comment]
Great!  You can still probably use the Reverter module in order to save/revert config changes, if it helps you out.

https://letsencrypt.readthedocs.org/en/latest/api/client/reverter.html
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/reverter.py

Before you make changes to a configuration file... you can add the files to a checkpoint.
add_to_checkpoint(save_files, save_notes)
or
add_to_temp_checkpoint(save_files, save_notes) <- This allows you to save challenge configuration changes separately and provides some guards to make sure permanent and temporary config changes don't collide with each other.

Before you create any new files... call
register_file_creation(temporary, *files)

When you are done with a significant amount of work... (issued a cert, performed an enhancement), call
finalize_checkpoint(title)

To revert temporary changes (cleanup from a challenge)
revert_temporary_config()

In case of a program crash, Control-C etc... you can restore the last finalized_checkpoint with...
recovery_routine()

Note: This class also provides many of the installer methods...
view_checkpoints()
rollback_checkpoints(N) 

Example of Basic Usage...
https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/augeas_configurator.py#L99

**Comment by lutter** [comment]
I've just updated the Augeas lens for Nginx (https://github.com/hercules-team/augeas/pull/225) and would love to hear feedback on whether that is sufficient for lets-encrypt's purposes and/or how it fails.

To try out the lens from the PR easily, download https://raw.githubusercontent.com/lutter/augeas/lns/nginx/lenses/nginx.aug and store it in /usr/share/augeas/lenses and run augtool. If you just want to make sure that your particular `nginx.conf` works, you can do something like

    augtool -A -t 'Nginx incl /path/to/nginx.conf' 'print /augeas//error'

If that prints nothing, all is well.

**Comment by diracdeltas** [comment]
@lutter thanks, i'll take a quick look.

I have basically rolled our own nginx parser at this point, but Augeas is nice because of the path traversal methods and the save functionality. WIP branch at https://github.com/diracdeltas/lets-encrypt-preview/tree/feature/nginx

**Comment by diracdeltas** [comment]
This is basically functional now that #351 and #387 are merged! :dancer:

**Comment by kuba** [comment]
Can we close it for now, @golodhrim?
