### ISSUE TITLE
TODO list for new contributors!

### ISSUE THREAD

**Issue by lexelby** [letsencrypt/letsencrypt#384]
Hi!  I'd like to help out if I can.  I saw on twitter that you'd like folks to write tests for boulder, but I don't know Go and would rather help out where I can immediately.  Where might an experienced Python programmer best help?

I saw the contributing doc and will be going through the steps there.  Should I then just start picking off posted issues and submitting PRs?

**Comment by devanp92** [comment]
+1

**Comment by kuba** [comment]
Hey, guys :) I think that going through existing GitHub issues is not a bad idea (e.g. #413), but I would be slightly afraid that only couple of them will make sense to newcomers. Grepping the source code for `TODO` items might find a lot smaller and more narrowly scoped tasks that could be easy to pick up.

In general we're aiming for 100% unit test coverage. If you could help in that, then please do! You could also perform the functional tests by running the CLI binary and report bugs here, on GitHub.

FYI @jdkasten is currently reworking the Apache plugin, so it's not worth to go into `letsencrypt_apache` stuff because you'd interfere with his work.

**Comment by bmw** [comment]
Unfortunately, this is largely outdated so I'm closing this issue. There is a label "Good Volunteer Task" which is a good place to start. If you're struggling to find something to do, please contact us and we'd be happy to give you some direction. Feel free to contact me personally if you prefer.
