### ISSUE TITLE
"run" should be the default, not a specific verb

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#442]
@kuba's <tt>cli</tt> branch got the CLI & CLI help closer to where it needs to be, but it added a "run" verb which doesn't really make sense.  "Run" should clearly be the default behaviour of the agent.

Kuba are you up for taking this?

**Comment by kuba** [comment]
I'll look into that after 27th of May

**Comment by pde** [comment]
@kuba nudge

**Comment by kuba** [comment]
Sorry. CLI work is blocked on #440 and #469. I also picked some higher priority tasks since then.

Nevertheless, I don't think that having optional verb (`run`) is:

1. Possible to implement with `argparse`/`ConfigArgParse` (without nasty hackery).
2. Easy to implement or sensible at all. For instance, how would you handle arguments specific to `run` subparser, when the verb is absent?

Do you know any tool that behaves this way? I can't think of any.

Maybe you want optional `--action {run,auth,...}` instead (or indeed, mutually exclusive `--revoke`, `--run`, ..., i.e. the previous design)? However, this doesn't give us a clear way of specifying arguments specific to given action... c.f. http://stackoverflow.com/a/6394994 ("If the command is optional, then this makes the command an option.") or http://stackoverflow.com/a/5176820 ("I don't think you want to use subcommands. Subcommands are used when the available options and positional arguments change depending on which subcommand is chosen.") and other quick google results

Maybe we should have separate CLI tools? Or maybe one tool for `run`, and another for all other actions?

**Comment by bmw** [comment]
As pointed out by @Jadaw1n, this only works if no other flags are specified on the command line. For example, `letsencrypt --text` doesn't work and instead the user has to type `letsencrypt --text run`.

**Comment by pde** [comment]
Should be fixed by #863
