### ISSUE TITLE
Remove Python 2.6 requirement from project

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#515]
With the addition of #513.  I think all developers are in favor of removing Python 2.6 from the project.  It was brought up previously by @kuba, and I believe we will only run into more issues into the future.

**Comment by kuba** [comment]
At this point, I think that it might be quite feasible to (semi-)support Python 2.6 at launch: code base is not that unstable.

A lot of effort has been already put into Python 2.6 support, so IMHO we should discard it only if we hit major issue (e.g. dependency exists only for Python 2.7+). If there is a chance that user can configure the environment by installing correct dependency versions, she should be able to run `letsencrypt` without `SyntaxError`s etc.: Travis CI for `TOXENV=py26` should be kept as a guarantee. That being said, I consider upstream `jsonschema` problem in #513/#517 to be a minor issue.

Many people are still using very old platforms, and bigger user coverage means bigger success for Let's Encrypt.  On the other hand, the same argument can cause bigger launch failure - there might be further Python 2.6 problems that we were not able to catch before release. We can "fix" it by saying that this support is experimental/deprecated (or not mentioning the official support at all) instead of leaving people disappointed and/or surprised.

**Comment by jdkasten** [comment]
Closing this for now...

**Comment by kuba** [comment]
@jdkasten, please reopen: "The last release of mock to support 2.6 was 1.0.1. mock 1.1.0 and above require Python 2.7 or higher." (https://github.com/testing-cabal/mock/blob/6f72979c5886a91a82395aaf0b9e14e9f6e0e076/README.txt), http://lists.idyll.org/pipermail/testing-in-python/2015-July/006492.html

Quick fixed in https://github.com/kuba/letsencrypt/commit/4ebc20402b3ca492ac3a0ca2c07e98fd21e29699

**Comment by jsha** [comment]
@kuba: I hear your point about how much work has been put into Python 2.6 support so far. However, it sounds like there is still occasional work resolving new Python 2.6 compat issues, and it's creating a drag on development. Here's my proposal: Let's official de-support Python 2.6 from now through launch + 2 months. We'll remove it from our unittest matrix and not worry about compat issues. Then, after we launch, we can evaluate how many support requests we get from people who have Python 2.6 but not Python 2.7. If there's enough interest, we can fix up any incompatibilities that have cropped up in the meantime.
