### ISSUE TITLE
Renewer assumes live and archive directories are nearby each other

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#520]
It looks like the live cert symlinks to "../../", implying that live_dir and archive_dir in the config must have a specific relationship to each other, which is not enforced. We should either symlink an absolute path, or enforce that relationship of the config parameters.

$ ls -l /tmp/tmpA9yaoZ/work/foo.com/cert.pem
lrwxrwxrwx 1 jsha jsha 31 Jun 19 13:55 /tmp/tmpA9yaoZ/work/foo.com/cert.pem -> ../../archive/foo.com/cert1.pem

**Comment by kuba** [comment]
Relationship is enforced in #473, where you can only set `--config-dir` and `--work-dir`, but not any other directory contained within.

**Comment by schoen** [comment]
Did #473 make it impossible to specify inconsistent versions in a *lineage* config file?  Definitely the logic as I implemented it around lineage configurations has the problem that @jsha identifies here, so I would expect it's still conceivably a problem in that context.  But I guess #473 has made it so that you can't easily create this problem with the systemwide configuration.

**Comment by kuba** [comment]
#473 made it impossible to specify directories in the lineage config file. It also reduced paths arguments to `--config-dir` and `--work-dir` only. As long as `constants.py` is sane (relative location of different directories doesn't change), reported issue will never happen. If https://github.com/kuba/letsencrypt/commit/040f434a61dad55afd2d08a667ec4d85f4124a0d#diff-c74d3ad4d86d0804f64e9354fa460b94R36 is uncommented, our integration tests will catch problematic `constants.py`.

**Comment by kuba** [comment]
That line is fixed in https://github.com/letsencrypt/letsencrypt/pull/554, so this issue can be closed as soon as the PR is merged.
