### ISSUE TITLE
No Configurators (Authenticator and Installer) installed should suggest auth verb

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#611]
If the user does not have any fully supported systems installed, the client should at least be informed about the 'auth' verb.

Location: after the pick_configurator call in cli.py
https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L181

May be implemented with a display notification() mesage

**Comment by bmw** [comment]
The description of this problem is out of date. It's currently about this [line](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L330). We should continue to just return a string, but we should have a better error message. Perhaps we should have different error messages depending on whether there is no installer, no authenticator, or both.

**Comment by pde** [comment]
Done.
