### ISSUE TITLE
Request single-identifier certs by default

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#627]
In a discussion today with @jsha about #411, he proposed the somewhat radical possibility of having the client deliberately get separate and independent certs by default for every requested name. For example, if you simultaneously asked for example.org, example.com, and example.net certs, the client would actually make 3 requests -- one for www.example.org and example.org, one for www.example.com and example.com, and one for www.example.net and example.net. These would be three separate cert lineages which could then be renewed (or revoked) completely independently of one another.

This would be the default behavior, and the present behavior of attempting to get all of the names in one cert would be available as a non-default option.

The reason I think @jsha advocated this is that that it automatically solves #411 and #318 because normally certs are just totally independent of one another. If you need to renew one, you renew that one, and your success or failure at renewing it simply doesn't affect any other cert that you possess. So if you had certs for 100 names and then one of the names got transferred to someone else, you would be able to succeed with 99 renewal requests, and 1 would fail, yet there would be no interference or delay.

In general, this would have the following advantages:

* More reliable and straightforward renewal and revocation
* Easy handling of cases where a single name gets transferred or expires
* Better privacy for servers (not automatically revealing all sites that they host)
* Less network traffic to LE cert users (due to smaller certs)
* Better crypto key diversity, less target aggregation

And the following disadvantages:

* Greater load on the CA
* Greater issuance volume
* Potentially greater latency for initial issuance or renewal (due to reduced request parallelization)
* Loss of compatibility with non-SNI clients
* Worse privacy for clients that could otherwise somehow have avoided the SNI request (they now can't avoid revealing which virtual host they were interested in)

@jsha also argues that for sites that specifically need large SNI certs because of a conscious engineering judgment, the ability to get those would still be available to them (using the existing protocol and issuance mechanisms, and optionally a new command-line flag if they're using our software).

Cc @pde, @jdkasten.

**Comment by schoen** [comment]
Also directly relevant to #369 (the question is which default to have).

**Comment by jsha** [comment]
Updated title to be a little clearer. The BRs require that names go in the subjectAlternativeName field, regardless of how many of them there are. The Subject CN field is deprecated. So really this is about how many names the official Let's Encrypt client would request in each cert by default.

I don't have the data handy, but there is significant overlap between non-SNI browsers and non-SHA256 browsers. It's not 100%. There are some non-SNI browsers that do support SHA256. We should find out which ones. Any browser without SHA256 is immediately off our supported list, so we don't have to worry about those.

There's an additional advantage to getting single-identifier certs by default: reduced handshake size, meaning faster connection times.

Two other notes:
 - Subscribers are of course free to request multi-identifier certs, but we may not support them in the auto-renewer of the official client on day 1.
 - This is a decision that we can change down the road. I.e. if we default to single-identifier at launch, we can change the default in subsequent client releases. To me, this argues for launching with single identifier by default since it means we can do something simple and robust, reducing the risk to our launch readiness.

**Comment by schoen** [comment]
Thanks, your change of the title is much clearer -- I was just using "SAN cert" in the very informal sense.

My intuition is that this is a change that makes things typically easier for the client and harder for the server (just in terms of load, not in terms of specific code changes). I'm not sure whether it makes things more intuitive or less intuitive for the sysadmin. Since I'm a client developer, it would make things easier for me.

**Comment by jsha** [comment]
Speaking from the server side, I think the difference is negligible. So we should go ahead and do what is most straightforward in the client, barring other considerations (like SNI support).

**Comment by jsha** [comment]
Fortunately I wrote this down a while ago: https://twitter.com/j4cob/status/522890941158670336. These are the browsers you lose for any given feature (SSLv3 means disabling SSLv3):

SSLv3: IE6 on any XP.
SHA-1: IE6,7,8 on XP < SP3.
SNI: IE6,7,8 on any XP.
https://en.wikipedia.org/wiki/Transport_Layer_Security#Web_browsers
https://en.wikipedia.org/wiki/Server_Name_Indication#Support

Additional research today:

Android 2.3+ supports SHA256 but not SNI
Android 3.0+ supports both SNI and SHA256.

So SNI differentially loses MSIE on XP service pack 3 (but not other browsers on XP), and Android 2.3 (but not earlier Androids).

**Comment by jsha** [comment]
According to Google's numbers from June 2015, Android 2.3 accounts for 5.6% of active devices: http://phandroid.com/2015/06/01/android-50-lollipop-platform-distribution-numbers-june-2015/. Google's numbers understate older Android versions because they only count devices accessing the Play Store. There are a large number of lower-end Android devices out there that do not ship with the Play Store.

According to (w3counter)[http://www.w3counter.com/globalstats.php?year=2015&month=6], Windows XP has 5.92%, and IE8 has 1.86%. IE6 and IE7 don't even show up on the chart. IE9+ isn't supported by Windows XP. Unfortunately it's impossible to backformulate from those numbers because XP usage and IE6/7/8 usage are correlated.

**Comment by tankerkiller125** [comment]
Considering that windows xp isn't even supported by Microsoft (thus no more security updates for IE8 or XP) Would it even make sense to attempt continued support for them?

**Comment by bmw** [comment]
Since I don't believe this is critical and the client has implemented the opposite behavior, I'm closing this issue.
