### ISSUE TITLE
Renewer should register symlink change with reverter

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#646]
The renewer will need to use the reverter or a reverter like mechanism to register symlink change updates so that they can be rolled back appropriately.

**Comment by schoen** [comment]
There's kind of an interesting question about how to handle certs that were issued more recently than the cert that the user wants to use. I think we had an idea about renaming them so that they no longer appear to be in the same lineage, maybe?

The problem with this is that if the user reverts a symlink to an older cert version in the same lineage, but has autodeploy turned on, the renewer might end up changing the symlink back again in the other direction (reasoning that there's a newer certificate available within the same lineage, so once the autodeploy period is reached, that newer certificate ought to be used).

**Comment by jdkasten** [comment]
Technically, the newer certificate should be registered as "created"  ```reverter.register_file_creation()``` so that it will also be removed when a rollback happens.

**Comment by bmw** [comment]
While I didn't use the `reverter`, this was closed by #970.
