### ISSUE TITLE
Useable for intranet / behind FW servers?

### ISSUE THREAD

**Issue by mvdkleijn** [letsencrypt/letsencrypt#648]
I have a question concerning useability for intranet based / behind the firewall servers.

We like to change everything to HTTPS, including our intranet servers, and (at least personally) I'd like to do that with "normal" certs, i.e. not self-signed. Less trouble with pushing our self-signing root cert to clients, trust store management etc. etc. etc.

I thought letsencrypt would be the ideal alternative, but from reading the specs etc I'm getting the impression that using letsencrypt behind the firewall might be difficult if not impossible.

Is it possible? Perhaps in manual mode?

**Comment by schoen** [comment]
Are the names that you want the certs for publicly resolvable?

Will there be a server that responds to those names that can at least temporarily be contacted by the public during the issuance process?

If both of these things are true, it should be possible to use Let's Encrypt. If not, probably not; Let's Encrypt can only certify things that it can directly verify (by connecting to hosts referred to by the subject names in the certificate, or otherwise confirming public records related to these names).

Let's Encrypt will definitely not issue certs whose existence or contents needs to remain secret. All of the certs that the CA issues will be published.

**Comment by mvdkleijn** [comment]
Some of them will be, but most not. I guess letsencrypt is useless then for our use case.

I'll read up a little more on the publishing of certs you mentioned because I must've missed that somewhere.

**Comment by kseltar** [comment]
how can i do it?
........................................./--(my public service on mydomian.tld)
(internet)-(mydomain.tld)<
..........................................\---mycloudsubdomain(separated).mydomain.tld
