### ISSUE TITLE
Let's Encrypt cannot access /etc/letsencrypt

### ISSUE THREAD

**Issue by iggyvolz** [letsencrypt/letsencrypt#649]
$ sudo bash
Password:
bash-4.3# letsencrypt -d blahblah.local auth
/etc/letsencrypt exists, this client can't access it
bash-4.3# 

Even though /etc/letsencrypt exists, and is chmod 777'd, and I'm logged in as root.

**Comment by jdkasten** [comment]
Hi @iggyvolz, sorry about the trouble. This is related/duplicate of #552.  The code doesn't work so well if you are modifying permissions or running the client with different users.  This is related to potential privilege escalation issues.

The quick solution is to simply delete the work-dir and config-dir  (/etc/letsencrypt, and /var/lib/letsencrypt)  and run the client only as a single user.  You can also specify paths which you own as --config-dir /work-dir.

This issue is filed as a requirement for launch and will be fixed soon.

**Comment by jdkasten** [comment]
If you did originally run it as root it may be looking for 755 on the directory. (Yes, it is an issue that will be fixed)
