### ISSUE TITLE
Unable to run the command: apache2ctl configtest

### ISSUE THREAD

**Issue by N0YB** [letsencrypt/letsencrypt#739]
Fresh CentOS 7 Install

yum install httpd (httpd-2.4.6-31.el7.centos.1.x86_64)
yum install mod_ssl (mod_ssl-2.4.6-31.el7.centos.1.x86_64)

./venv/bin/letsencrypt -d subdomain.tld.com auth

Results in this message for option #1:
Apache Web Server - Alpha (apache) [Misconfigured]
More Info:
Reported Error: Unable to run the command: apache2ctl configtest

Run in Standalone Mode obtained certificate

./venv/bin/letsencrypt -d subdomain.tld.com run
"Unable to run the command: apache2ctl configtest"

Looks like the command should be apachectl configtest

**Comment by centminmod** [comment]
probably due to Letsencrypt client being Ubuntu OS centric and not accounting for CentOS specific package and file names

**Comment by N0YB** [comment]
If I create an apache2ctl sym link to apachectl then only manual and standalone authentication modes are available (no Apache Web Server mode).
And letsencrypt -d domain run reports that "Configurator could not be determined".

**Comment by kuba** [comment]
Rather than messing with your distribution (e.g. symlinking) I would suggest to `letsencrypt --apache-ctl apachectl -d domain run`. You may also need to update `--apache-enmond`, `--apache-dismod`, `--apache-init-script`.

Note, that all flags can be set using [configuration file](http://letsencrypt.readthedocs.org/en/latest/using.html#configuration-file) (although there are some upstream problems currently: https://github.com/bw2/ConfigArgParse/issues/26).

Could you please report back necessary values, so that we can update documentation?

**Comment by N0YB** [comment]
Think --apache-server-root should be /etc/httpd.  The current default appears to be /etc/apache2.
Haven't made any progress on the other options.  Other than that the default for init script /etc/init.d/apache2 does not exist.

**Comment by jdkasten** [comment]
Other distributions haven't attempted to be tackled yet.

Off the top of my head, here is what needs to be changed.
1.  Default locations (easy)
2.  Installing/enabling modules
3.  Virtual host loadout (pretty easy)  - we need to change the one call to sites-available -> location of server_root  (or a more apt place if there is one)

**Comment by bmw** [comment]
Closing this as a more specific form of #788.
