### ISSUE TITLE
Support for multi-OS Apache

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#788]
The Apache plugin has been designed and tested on the Ubuntu/Debian layout.  It shouldn't be that difficult to adapt the code to work with other OS configurations easily, but some work needs to be done.

Some initial ideas...

https://community.letsencrypt.org/t/installer-throwing-error-message/1120/9?u=jdkasten

Also, failure should be graceful for unsupported layouts...

**Comment by jdkasten** [comment]
This might be true of nginx too.  (I haven't looked)

All binaries should be confirmed to be present in the .prepare() method.  If one or more are missing, a MisconfiguredError should be thrown detailing what is missing.

**Comment by jdkasten** [comment]
Related https://github.com/letsencrypt/letsencrypt/issues/644

**Comment by jdkasten** [comment]
more help.... in letsencrypt/le_util.py there is an exe_exists function that checks to make sure an executable exists.  It may be helpful.

**Comment by aetherknight** [comment]
I would propose providing some additional apache arguments might help with supporting many cases out there. I use Gentoo, whose setup for apache is fairly different from Debian-based systems:

* Gentoo has separate apache2ctl and apache2 commands, whereas the letsencrypt-apache plugin seems to want a single command to both manage the service and to query apache's configuration. On Gentoo with apache 2.4, `apache2ctl` is a wrapper script that forwards commands to the init script (it can start, stop, configtest, etc.), while the `apache2` command accepts various flags, such as the "-D DUMP_RUN_CFG" used to get the runtime apache configuration.
* Gentoo makes heavy use of the -D flags for modules.

The existing `--apache-ctl` option does not provide enough flexibility for both of these cases.

* Gentoo uses a single /etc/apache2/vhosts.d directory, instead of having /etc/apache2/sites-enabled and a sites-available.

I don't think there is anything to configure this either, since sites-enabled is hard-coded in several places.

**Comment by jdkasten** [comment]
Sounds appropriate to me

**Comment by pde** [comment]
I think before GA we need to make this work on every distro we know how to bootstrap, or pull those distros from the `letsencrypt-auto` bootstrap logic.

**Comment by pde** [comment]
I'm going to take this ticket for a while, and see what I can do with it.

**Comment by pde** [comment]
I have an early start on this, but jsha has convinced me that we should kick this out of 1.0 at least until the various showstoppers are done.

**Comment by pde** [comment]
@swartzcr one conclusion from research: the [complex test](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L141) for apache installation should be replaced with a simpler one that checks for `apache2ctl`, though we will need to ensure we have functional alternatives to Debian's `a2enmod` etc.

**Comment by pde** [comment]
Giving this to @joohoi for the time being.
