### ISSUE TITLE
--server flag doesn't work without subcommand

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#820]
Steps to reproduce:

`letsencrypt --server https://acme-staging.api.letsencrypt.org/directory`

Result:

`letsencrypt: error: unrecognized arguments: --server https://acme-staging.api.letsencrypt.org/directory`

Expected result:

Same as default `letsencrypt` command, authorize names and set up a cert, but with a non-default server URL.

**Comment by bmw** [comment]
The CLI needs some work at the moment. You expected the right result but to make it work currently you need to run:
```
letsencrypt --server https://acme-staging.api.letsencrypt.org/directory run
```

**Comment by pde** [comment]
The issue here is that argparse is only happy with this flag being provided *before* a subcommand.  So right now, this works:

`letsencrypt --server https://api.eg/ auth`

while this doesn't:

`letsencrypt auth --server https://api.eg/`

Needless to say, this is terrible behaviour.  I'll see what I can do about it...

**Comment by pde** [comment]
And of course, the handling of flags specific to subcommands is the opposite; `letsencrypt --csr file.csr auth` will fail :(.

There are a number of [ugly solutions](https://stackoverflow.com/questions/23296695/permit-argparse-global-flags-after-subcommand) to this problem discussed on stack exchange.

Another option, not discussed there is:

- use my hackish preprocessing of the command line to always move the verb to the very end
- move all subcommand arguments into their own argument groups, rather than attaching them to the subcommands

Downsides:

 - no erroring out if a nonsensical subcommand argument is provided when that subcommand isn't running.  Is that actually a problem, I wonder?  It seems we might be overzealous in this sense right now: if `--csr` makes sense for `auth`, does it not make sense for `run`

**Comment by kuba** [comment]
Note, that we use `ConfigArgParse` for config file parsing. I think that if you move stuff to subcommands only, you will likely break config file parsing.

IMHO this is not that terrible behavior. It's exactly the same as, e.g. in `git`: `git --config foo.bar=baz subcommand --arg` works, but `git subcommand --config foo.bar.baz --arg` does not.

**Comment by pde** [comment]
I find the behaviour really frustrating from most tools that have it.  In git's case it's rare to use global flags so it's not as much of a hassle.

I'm not talking about moving things to subcommands; I'm talking about moving them all *out* of subcommands and into argument groups that match the subcommands.
