### ISSUE TITLE
Detect when chosen web server isn't listening on necessary port

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#842]
Steps to reproduce:

1. Install Apache and Nginx. Run Nginx and leave Apache stopped.
2. Run `letsencrypt  --text --agree-eula --agree-tos -d lastbart.at -a apache auth`

Actual result:

`Failed authorization procedure. lastbart.at (dvsni): connection :: The server could not connect to the client for DV :: Failed to connect to host for DVSNI challenge`

Expected result:

Client gives an error saying that Apache doesn't have access to port 443 or isn't listening on port 443.

One can also reproduce with only Apache installed by editing ports.conf so that it doesn't include port 443.

**Comment by jdkasten** [comment]
Thanks!  This should be fixed with proper error recovery on the restart call.  We might want to do a config_check if error detection with restart isn't working well enough.  It appears that the return code doesn't always return an error.  (Probably due to the race condition @bmw found with Apache scripts)

Anyway, it should detect the failure and run the ```recovery_routine''' with the error.  This hasn't been worked on yet.

**Comment by jdkasten** [comment]
I am surprised though that... ```Listen 443``` wasn't auto added by the plugin when running.  Thanks for reporting this... sounds like I will have my hands full making sure things are nailed down.

**Comment by jsha** [comment]
I tried to reproduce this a couple times and found that it did not reproduce: instead, it seems like Listen 443 was cleanly auto added and then removed. I'll reopen if I can make it happen again.
