### ISSUE TITLE
Remove Nginx from list of supported plugins

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#866]
We have multiple reports that Nginx support is completely broken and breaks people's web servers when they run it. We should remove Nginx from the ncurses UI and from the command line help until it's fixed. Otherwise early beta participants will be very confused.

**Comment by centminmod** [comment]
i hope Nginx isn't removed from simplefs plugin https://github.com/letsencrypt/letsencrypt/pull/757 whenever it's merged as simplefs plugin works fine for my custom Nginx server where i auto generate the needed https before running the letsencrypt client in simplefs mode.

**Comment by bmw** [comment]
@centminmod, while I have other worries about the effectiveness of the SimpleFS plugin, it is server independent so you don't have to worry about Nginx support being removed there.

**Comment by kuba** [comment]
Rather than removing it from the UI, we should just make sure `letsencrypt-nginx` package is not installed in the user bootstrap scripts: this way it'll not register setuptools entry point and will not be present in the UI/help, but... if someone really wants to install it, it will appear in the UI / help. AKA: don't use `hidden = True`! :)

**Comment by bmw** [comment]
Kuba's suggestion for not installing `letsencrypt-nginx` was implemented [here](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-auto#L73).
