### ISSUE TITLE
VestaCP with LetsEncrypt - untrusted

### ISSUE THREAD

**Issue by dvapelnik** [letsencrypt/letsencrypt#873]
I'm using VestaCP control panel. I have four files from letsencrypt:
```
# ls -l /etc/letsencrypt/live/<my.domain.com>
total 0
lrwxrwxrwx 1 root root 38 жов  1 17:21 cert.pem -> ../../archive/<my.domain.com>/cert1.pem
lrwxrwxrwx 1 root root 39 жов  1 17:21 chain.pem -> ../../archive/<my.domain.com>/chain1.pem
lrwxrwxrwx 1 root root 43 жов  1 17:21 fullchain.pem -> ../../archive/<my.domain.com>/fullchain1.pem
lrwxrwxrwx 1 root root 41 жов  1 17:21 privkey.pem -> ../../archive/<my.domain.com>/privkey1.pem
```
I got them through `letsencrypt auth` and `standalone authentifacator (standalone)` for my.domain.com and www.my.domain.com (space separated).
I took `cert.pem` and write it in `SSL Certificate` field on control panel
I took `privkey.pem` and write it in `SSL Key` field on control panel
I took CA from https://letsencrypt.org/2015/06/04/isrg-ca-certs.html and write it in `SSL Certificate Authority / Intermediate` field on control panel (I tried all three CA and `chain.pem` and `fullchain.pem`)

But in all this cases cert is not trusted on browsers (Chrome, Firefox)

What I doing wrong?

**Comment by bmw** [comment]
Hi @dvapelnik. The problem is that Let's Encrypt is still under development and is not yet issuing trusted certificates. We will begin issuing certificates that will be trusted by all major browsers during the beta period which you can apply for [here](https://goo.gl/forms/kf0IGCeAk5). We will start issuing trusted certs to the general public the week of November 16th.

**Comment by dentee** [comment]
I used https://gethttpsforfree.com/ with VestaCP which worked great. Had to stop NginX for creation, but no need of client...
