### ISSUE TITLE
Travis badge shows most recent build, not master

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#927]
I've noticed earlier today [on PyPI](https://pypi.python.org/pypi/letsencrypt) that Travis badge was red and linked to build of a PR (https://travis-ci.org/letsencrypt/letsencrypt/builds/84240759, coincidentally failing) instead of the build of the latest `master`.

**Comment by FloFra** [comment]
Sounds like a Travis bug or like you looked at an old description page since the badge has been referring to the master branch for a while now.

The PyPi description is based on the Readme since the end of January (47e4921) and the Readme has been referring to the master branch since end of February (e14beb2).

**Comment by marcogario** [comment]
This is probably a bug of Travis, see this bug report [1]. The last comment [2] seems to describe exactly the same situation.

[1] https://github.com/travis-ci/travis-ci/issues/655
[2] https://github.com/travis-ci/travis-ci/issues/655#issuecomment-105060078

**Comment by ArchimedesPi** [comment]
`README.rst` points at the **master** branch on Travis:
```rst
.. |coverage| image:: https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master
   :target: https://coveralls.io/r/letsencrypt/letsencrypt
   :alt: Coverage status
```
I've had this problem before, it's on their end. This can probably be closed.

**Comment by bmw** [comment]
Looks like this is a known problem with Travis :frowning: Thanks for looking into the issue.

Closing for now.
