### ISSUE TITLE
Give friendlier errors on new error types from server

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#946]
Currently, if the client receives an unrecognized error type from the server (e.g. rate limited), it gives an unfriendly error:

```
An unexpected error occurred.
ClientError: (<Response [429]>, DeserializationError("Could not decode 'typ' (u'urn:acme:error:rateLimited'): Deserialization error: Error type not recognized",))
```

Instead, the client should expect that error types will be added that it does not recognize, and report them to the user similarly to other errors, including the error detail message.

I think this is fairly high priority to fix, because otherwise it prohibits Boulder from using meaningful error types.

**Comment by kuba** [comment]
(At least) at the time I was writing the code, specification didn't allow (or wasn't clear if it's possible for) error types to be extended by the concrete implementation. In fact, it's slightly confusing even now: "To facilitate automatic response to errors, this document defines the following standard tokens for use in the "type" field (within the "urn:acme:" namespace):". Only the word "standard" hints that there might be some non-standard types... Can we update spec to be explicit about it? Are types allowed to be outside the `urn:acme:` namespace? Do we allow unrecognized types (such as this one, as it's not mentioned in the spec) in the `urn:acme:` namespace?

This should be tagged with `spec-compliance` rather than `ui/ux`.

**Comment by jsha** [comment]
I have a PR against the IETF ACME repo: https://github.com/ietf-wg-acme/acme/pull/17

**Comment by kuba** [comment]
Given https://github.com/letsencrypt/letsencrypt/pull/974 I think we can lower down prio, and move to 1.0-nice. @bmw?

**Comment by bmw** [comment]
Didn't see your comment here when I changed the milestone.

As you can see, I agree with you. While it's not an ideal solution, we can do the same thing we did in #974 if new error types are introduced as a quick fix until a long term solution is in place.
