### ISSUE TITLE
Exception handling in renewer

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#958]
We should move `cli._handle_exception` to `cli_common.handle_exception` and reuse it in `renewer`.

**Comment by bmw** [comment]
In addition to this, if the `renewer` cannot access `configs_dir` or `renewal_configs_dir`, either because they don't exist or the user has insufficient permissions, the program will exit with an `OSError`. Ideally, these errors should be caught and the `renewer` should exit with an error message saying there is nothing to renew. Be sure this error message is only displayed for these directories, as the exception could have been raised due to problems with a different directory.

**Comment by bmw** [comment]
The renewer was moved into the client and this issue no longer applies.
